In [1]:
#encoding: utf-8
import numpy as np
import pandas as pd
import xgboost as xgb

from dateutil import parser
from datetime import datetime
import math
data_path = "../data/"
result_path =  "../data/result/"
feature_path =  "../data/feature/"
analysis_path =  "../data/analysis/"
function_path =  "../data/function/"

# reading data
train = pd.read_csv(data_path + 'train.csv')
test = pd.read_csv(data_path + 'evaluation_public.csv')
entbase = pd.read_csv(data_path + '1entbase.csv')
alter = pd.read_csv(data_path + '2alter.csv')
branch = pd.read_csv(data_path + '3branch.csv')
invest = pd.read_csv(data_path + '4invest.csv')
right = pd.read_csv(data_path + '5right.csv')
project = pd.read_csv(data_path + '6project.csv')
lawsuit = pd.read_csv(data_path + '7lawsuit.csv')
breakfaith = pd.read_csv(data_path + '8breakfaith.csv')
recruit = pd.read_csv(data_path + '9recruit.csv')
qualification = pd.read_csv(data_path + '10qualification.csv')

/opt/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/opt/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
import math
def translateYear(date):
    if type(date) == float:
        return np.nan
    year = int(date[:4])
    month = int(date[-2:])
    return (year-2015)*12 + month

def translateYearALTER(date):
    if type(date) == float:
        return np.nan
    year = int(date[:4])
    month = int(date[-2:])
    return (year-2013)*12 + month

def translateYearRECRUIT(date):
    if type(date) == float:
        return np.nan
    year = int(date[:4])
    month = int(date[-2:])
    return (year-2008)*12 + month

def translateYearFB(date):
    if type(date) == float:
        return np.nan
    year = int(date[:4])
    month = int(date[5:-2])
    return (year-2010)*12 + month

import math
def translateEnddate(date):
    if type(date) == float:
        return 2015
    year = int(date[:4])
    return year

def get_HandE(new_right, col_name, prefix_index):
    right_type_HY_sta = new_right.groupby(['HY'])[col_name].agg({sum, max,min, np.mean}).add_prefix(col_name[: prefix_index] + '_HY_').reset_index()
    right_type_ETYPE_sta = new_right.groupby(['ETYPE'])[col_name].agg({sum, max,min, np.mean}).add_prefix(col_name[: prefix_index] + '_ETYPE_').reset_index()
    right_type_HYandETYPE_sta = new_right.groupby(['ETYPE', 'HY'])[col_name].agg({sum, max,min, np.mean}).add_prefix(col_name[: prefix_index] + '_HYandETYPE_').reset_index()
    
    new_right = pd.merge(new_right, right_type_HY_sta, on = 'HY', how = 'left')
    new_right = pd.merge(new_right, right_type_ETYPE_sta, on = 'ETYPE', how = 'left')
    new_right = pd.merge(new_right, right_type_HYandETYPE_sta, on = ['ETYPE', 'HY'], how = 'left') 
    
    new_right[col_name[:prefix_index] + '_HY_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_HY_mean'] 
    new_right[col_name[:prefix_index] + '_ETYPE_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_ETYPE_mean'] 
    new_right[col_name[:prefix_index] + '_HYandETYPE_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_HYandETYPE_mean']  
    
    return new_right

def get_HandEforEntbase(new_right, col_name, prefix_index):
    right_type_HY_sta = new_right.groupby(['HY'])[col_name].agg({max, np.mean, np.median}).add_prefix(col_name[: prefix_index] + '_HY_').reset_index()
    right_type_ETYPE_sta = new_right.groupby(['ETYPE'])[col_name].agg({ max, np.mean, np.median}).add_prefix(col_name[: prefix_index] + '_ETYPE_').reset_index()
    right_type_HYandETYPE_sta = new_right.groupby(['ETYPE', 'HY'])[col_name].agg({max, np.mean, np.median}).add_prefix(col_name[: prefix_index] + '_HYandETYPE_').reset_index()
    
    new_right = pd.merge(new_right, right_type_HY_sta, on = 'HY', how = 'left')
    new_right = pd.merge(new_right, right_type_ETYPE_sta, on = 'ETYPE', how = 'left')
    new_right = pd.merge(new_right, right_type_HYandETYPE_sta, on = ['ETYPE', 'HY'], how = 'left') 
    
    new_right[col_name[:prefix_index] + '_HY_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_HY_mean'] 
    new_right[col_name[:prefix_index] + '_ETYPE_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_ETYPE_mean'] 
    new_right[col_name[:prefix_index] + '_HYandETYPE_gap'] = new_right[col_name] - new_right[col_name[:prefix_index] + '_HYandETYPE_mean']  
    
    return new_right

def get_HandEandPforEntbase(df, col_name, prefix_index):
    df_PROV_sta = df.groupby(['PROV'])[col_name].agg({ max,np.mean, np.median}).add_prefix(col_name[: prefix_index]+ '_PROV_').reset_index()
    df_PROV_HY_sta = df.groupby(['PROV', 'HY'])[col_name].agg({ max,np.mean, np.median}).add_prefix(col_name[: prefix_index]+ '_PROVandHY_').reset_index()
    df_PROV_ETYPE_sta = df.groupby(['PROV', 'ETYPE'])[col_name].agg({max,  np.mean, np.median}).add_prefix(col_name[: prefix_index]+ '_PROVandETYPE_').reset_index()
    df_PROV_HY_ETYPE_sta = df.groupby(['PROV', 'HY', 'ETYPE'])[col_name].agg({max,np.mean, np.median}).add_prefix(col_name[: prefix_index]+ '_PROVandHYandETYPE_').reset_index()

    df = pd.merge(df, df_PROV_sta, on = 'PROV', how = 'left')
    df = pd.merge(df, df_PROV_HY_sta, on = ['PROV', 'HY'], how = 'left')
    df = pd.merge(df, df_PROV_ETYPE_sta, on = ['PROV', 'ETYPE'], how = 'left') 
    df = pd.merge(df, df_PROV_HY_ETYPE_sta, on = ['PROV', 'ETYPE', 'HY'], how = 'left') 
    
    
    df[col_name[:prefix_index] + '_PROV_gap'] = df[col_name] - df[col_name[:prefix_index] + '_PROV_mean'] 
    df[col_name[:prefix_index] + '_PROVandHY_gap'] = df[col_name] - df[col_name[:prefix_index] + '_PROVandHY_mean'] 
    df[col_name[:prefix_index] + '_PROVandETYPE_gap'] = df[col_name] - df[col_name[:prefix_index] + '_PROVandETYPE_mean']  
    df[col_name[:prefix_index] + '_PROVandHYandETYPE_gap'] = df[col_name] - df[col_name[:prefix_index] + '_PROVandHYandETYPE_mean']  

    return df

# Train

In [3]:
train = pd.read_csv(data_path + 'train.csv')
train['ENDDATE_n'] = train.ENDDATE.apply(translateEnddate)
new_train = train.drop(['ENDDATE', 'ENDDATE_n'], axis = 1)

In [4]:
entbase[entbase.ZCZB.isnull()]

,PROV,EID,RGYEAR,HY,ZCZB,ETYPE,MPNUM,INUM,ENUM,FINZB,FSTINUM,TZINUM
205866,12,s179317,1997,24.0,NaN,5,1.0,2.0,2.0,20.00,0.0,NaN
208414,12,s513597,1987,61.0,NaN,5,5.0,5.0,5.0,442523.23,62.0,NaN
253977,12,s241292,1996,65.0,NaN,5,NaN,1.0,0.0,NaN,0.0,NaN
394503,12,s140281,2011,52.0,NaN,8,NaN,1.0,0.0,NaN,0.0,NaN
396685,12,s299404,2012,72.0,NaN,5,NaN,1.0,1.0,NaN,0.0,NaN

In [5]:
len(entbase.EID.unique())

436798

In [6]:
len(alter.EID.unique())

136034

In [7]:
len(branch.EID.unique())

27736

In [8]:
len(invest.EID.unique())

30728

In [9]:
len(right.EID.unique())

120662

In [10]:
len(project.EID.unique())

8067

In [11]:
len(lawsuit.EID.unique())

10148

In [12]:
len(breakfaith.EID.unique())

1451

In [13]:
len(recruit.EID.unique())

41877

In [14]:
entbase.count()

PROV       436798
EID        436798
RGYEAR     436798
HY         436790
ZCZB       436793
ETYPE      436798
MPNUM      321207
INUM       433024
ENUM       433024
FINZB       34143
FSTINUM    431027
TZINUM       5448
dtype: int64

# Entbase Feature

In [15]:
entbase = pd.read_csv(data_path + '1entbase.csv')

In [16]:
entbase

,PROV,EID,RGYEAR,HY,ZCZB,ETYPE,MPNUM,INUM,ENUM,FINZB,FSTINUM,TZINUM
0,11,p13836,1980,51.0,480.0,13,25.0,1.0,1.0,98041.0000,17.0,NaN
1,11,p49137,1993,74.0,30.0,13,0.0,1.0,1.0,570.0000,3.0,NaN
2,11,p108756,2015,69.0,1000.0,6,2.0,1.0,1.0,1000.0000,0.0,NaN
3,11,p7320,2005,74.0,240.0,5,0.0,2.0,2.0,1500.0000,0.0,NaN
4,11,p194070,2014,51.0,100000.0,3,3.0,2.0,2.0,1000.0000,7.0,NaN
5,11,p120116,2009,51.0,800.0,6,3.0,1.0,1.0,5000.0000,4.0,NaN
6,11,p197225,2011,75.0,3000.0,6,4.0,8.0,1.0,10500.0000,13.0,NaN
7,11,p60345,1995,54.0,14200.0,5,0.0,2.0,2.0,11280.0000,5.0,NaN
8,11,p124661,2002,48.0,2800.0,7,0.0,22.0,4.0,100.0000,0.0,NaN
9,11,p107376,2004,51.0,50.0,6,0.0,2.0,2.0,100.0000,0.0,NaN
10,11,p154162,1982,55.0,1000.0,6,9.0,2.0,2.0,619318.0000,31.0,NaN
11,11,p8549,2015,51.0,7000.0,6,3.0,2.0,2.0,909980.0000,12.0,NaN
12,11,p2642,2013,51.0,510.0,6,0.0,2.0,1.0,1100.0000,1.0,NaN
13,11,p167536,2013,52.0,100.0,6,7.0,1.0,1.0,5590.0000,5.0,NaN
14,11,p77869,2011,72.0,1000.0,6,5.0,2.0,2.0,2000.0000,6.0,NaN
15,11,p167465,2012,51.0,50.0,6,1.0,1.0,1.0,3529.4118,2.0,NaN
16,11,p34337,1991,25.0,6800.0,5,0.0,2.0,2.0,8000.0000,5.0,NaN
17,11,p224672,2013,51.0,40000.0,16,NaN,4.0,3.0,40000.0000,6.0,3.0
18,11,p210667,2013,65.0,10.0,6,9.0,2.0,1.0,1319.3483,2.0,NaN
19,11,p29109,1986,53.0,150.0,17,4.0,1.0,1.0,13000.0000,31.0,NaN
20,11,p72115,2004,51.0,500.0,6,3.0,1.0,1.0,3000.0000,6.0,NaN
21,11,p159540,2010,70.0,2000.0,6,25.0,3.0,2.0,24250.0000,5.0,NaN
22,11,p226334,2015,58.0,1000.0,6,15.0,2.0,2.0,200000.0000,7.0,NaN
23,11,p225,2012,41.0,300.0,6,2.0,1.0,1.0,1000.0000,3.0,NaN
24,11,p164048,2015,60.0,500.0,6,3.0,2.0,1.0,2000.0000,1.0,NaN
25,11,p157646,2014,81.0,10.0,6,1.0,2.0,1.0,549.3298,4.0,NaN
26,11,p132503,2010,72.0,10100.0,16,NaN,2.0,2.0,10000.0000,0.0,1.0
27,11,p23164,2014,40.0,500.0,6,9.0,2.0,2.0,3811.1600,10.0,NaN
28,11,p45370,1992,38.0,2800.0,5,4.0,3.0,3.0,200.0000,0.0,NaN
29,11,p84560,1989,54.0,100.0,6,2.0,2.0,2.0,269.2000,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
436768,12,s64628,2012,75.0,10.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436769,12,s438115,2010,52.0,50.0,7,4.0,1.0,0.0,NaN,4.0,NaN
436770,12,s166272,2013,75.0,100.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436771,12,s155027,2012,51.0,200.0,7,1.0,1.0,0.0,NaN,1.0,NaN
436772,12,s367365,2012,51.0,110.0,7,1.0,1.0,0.0,NaN,0.0,NaN
436773,12,s138462,2015,51.0,300.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436774,12,s319387,2013,75.0,200.0,7,NaN,4.0,0.0,NaN,1.0,NaN
436775,12,s298513,2007,75.0,300.0,7,1.0,1.0,0.0,NaN,0.0,NaN
436776,12,s486365,2012,51.0,100.0,16,NaN,22.0,1.0,NaN,9.0,NaN
436777,12,s163049,2015,51.0,50.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436778,12,s464886,2000,75.0,2100.0,7,4.0,2.0,0.0,NaN,3.0,NaN
436779,12,s437336,2007,75.0,100.0,6,NaN,1.0,1.0,NaN,4.0,NaN
436780,12,s55914,2014,52.0,10.0,7,5.0,1.0,0.0,NaN,3.0,NaN
436781,12,s246522,2004,72.0,2500.0,7,2.0,2.0,0.0,NaN,8.0,NaN
436782,12,s383445,1999,52.0,30.0,7,1.0,2.0,0.0,NaN,1.0,NaN
436783,12,s235758,2007,74.0,50.0,7,1.0,1.0,0.0,NaN,2.0,NaN
436784,12,s260705,2003,51.0,50.0,7,NaN,2.0,0.0,NaN,0.0,NaN
436785,12,s29540,2013,70.0,1100.0,7,4.0,2.0,0.0,NaN,2.0,NaN
436786,12,s513207,2009,65.0,5000.0,3,1.0,2.0,0.0,NaN,5.0,NaN
436787,12,s493526,2010,52.0,10.0,7,NaN,3.0,0.0,NaN,0.0,NaN
436788,12,s232439,2006,75.0,3.0,8,NaN,1.0,0.0,NaN,0.0,NaN
436789,12,s243096,2015,87.0,50.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436790,12,s461479,2010,51.0,100.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436791,12,s242382,2013,51.0,500.0,7,1.0,1.0,0.0,NaN,0.0,NaN
436792,12,s440160,2013,52.0,100.0,7,NaN,1.0,0.0,NaN,0.0,NaN
436793,12,s143196,2015,75.0,10.0,7,2.0,1.0,0.0,NaN,4.0,NaN
436794,12,s429712,2014,52.0,100.0,7,2.0,1.0,0.0,NaN,0.0,NaN
436795,12,s5937,2013,59.0,500.0,7,NaN,4.0,0.0,NaN,0.0,NaN
436796,12,s262843,2012,59.0,10.0,7,2.0,2.0,0.0,NaN,4.0,NaN
436797,12,s175584,2014,52.0,100.0,7,NaN,1.0,0.0,NaN,0.0,NaN

In [17]:
EID_HY_ETYPE = entbase[['EID', 'HY', 'ETYPE']]

In [18]:
entbase.TZINUM.unique()

array([ nan,   3.,   1.,   2.,   8.,   6.,   4.,   5.,  11.,   7.,  12.,
        15.,  10.,  16.,  14.,   9.,  18.,  13.,  27.,  24.,  25.,  19.])

In [19]:
entbase['EID_NUMBER'] = entbase.EID.apply(lambda row: row[1:])
entbase['EID_NUMBER'] = entbase.EID.apply(lambda row: row[1:])

In [20]:
entbase.ZCZB.fillna(0, inplace = True)
entbase.MPNUM.fillna(0, inplace = True)
entbase.INUM.fillna(0, inplace = True)
entbase.ENUM.fillna(0, inplace = True)
entbase.FINZB.fillna(0, inplace = True)
entbase.FSTINUM.fillna(0, inplace = True)
entbase.TZINUM.fillna(0, inplace = True)


new_entbase = entbase.copy()
new_entbase['RGYEAR_gap'] = 2016 - new_entbase.RGYEAR
new_entbase['ZCZB_mul_YEAR'] = new_entbase['RGYEAR_gap'] * 100 / 65 * new_entbase['ZCZB']

In [22]:
new_entbase['2014_Policy'] = new_entbase['RGYEAR'].apply(lambda row: 1 if row < 2014 else 2)

In [571]:
HY_null_index = list(new_entbase[new_entbase.HY.isnull()].index)

In [572]:
for index in HY_null_index:
    row = new_entbase.loc[index]
    etype = row.ETYPE
    etype_record = new_entbase[new_entbase.ETYPE == etype]
    fillHY = (etype_record.HY.value_counts().reset_index())['index'][0]
    row.HY = fillHY
    new_entbase.loc[index] = row

/opt/anaconda/lib/python3.6/site-packages/pandas/core/generic.py:3110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [573]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(2)
tmp = new_entbase.copy()
tmp.drop(['EID','EID_NUMBER', 'TZINUM'], axis = 1, inplace = True)
poly_feature = poly.fit_transform(tmp)
colname = [('Poly_f' + str(i)) for i in range(poly_feature.shape[1])]

In [574]:
ploy_df = pd.DataFrame(poly_feature, columns = colname)
new_entbase = pd.concat([new_entbase, ploy_df], axis = 1)

In [575]:
new_entbase['n_ZCZB_DEL_FINZB'] = new_entbase['ZCZB_mul_YEAR'] - new_entbase['FINZB']
new_entbase['n_ZCZB_ADD_FINZB'] = new_entbase['ZCZB_mul_YEAR'] + new_entbase['FINZB']
new_entbase['MP2-FSTI2'] = new_entbase['MPNUM']**2 - new_entbase['FSTINUM']**2

#1.10
new_entbase['MP2+FSTI2'] = new_entbase['MPNUM']**2 + new_entbase['FSTINUM']**2
new_entbase['I2+FSTI2'] = new_entbase['INUM']**2 + new_entbase['FSTINUM']**2
new_entbase['E2+FSTI2'] = new_entbase['ENUM']**2 + new_entbase['FSTINUM']**2
new_entbase['I2+MP2'] = new_entbase['INUM']**2 + new_entbase['MPNUM']**2
new_entbase['E2+MP2'] = new_entbase['ENUM']**2 + new_entbase['MPNUM']**2

new_entbase['RGYEAR_mul_FINZB'] = new_entbase['RGYEAR_gap'] * new_entbase['FINZB']
new_entbase['RGYEAR_mul_I'] = new_entbase['RGYEAR_gap'] * new_entbase['INUM']
new_entbase['RGYEAR_mul_MP'] = new_entbase['RGYEAR_gap'] * new_entbase['MPNUM']
new_entbase['RGYEAR_mul_FSTI'] = new_entbase['RGYEAR_gap'] * new_entbase['FSTINUM']
new_entbase['RGYEAR_mul_E'] = new_entbase['RGYEAR_gap'] * new_entbase['ENUM']

In [576]:
new_entbase.MPNUM.unique().max(),new_entbase.INUM.unique().max(),new_entbase.ENUM.unique().max(),new_entbase.FSTINUM.unique().max(),\
new_entbase.TZINUM.unique().max()

(49261.0, 1900.0, 391.0, 27480.0, 27.0)

In [577]:
new_entbase.shape

(436798, 119)

version3

In [578]:
ZCZB_mul_YEAR_HandE = get_HandEforEntbase(new_entbase, 'ZCZB_mul_YEAR', len('ZCZB_mul_YEAR'))
MPNUM_HandE = get_HandEforEntbase(ZCZB_mul_YEAR_HandE, 'MPNUM', len('MPNUM'))
INUM_HandE = get_HandEforEntbase(MPNUM_HandE, 'INUM', len('INUM'))
FSTINUM_HandE = get_HandEforEntbase(INUM_HandE, 'FSTINUM', len('FSTINUM'))
RGYEAR_HandE = get_HandEforEntbase(FSTINUM_HandE, 'RGYEAR', len('RGYEAR'))


ZCZB_mul_YEAR_HandEandP  = get_HandEandPforEntbase(RGYEAR_HandE, 'ZCZB_mul_YEAR', len('ZCZB_mul_YEAR'))
MPNUM_HandEandP  = get_HandEandPforEntbase(ZCZB_mul_YEAR_HandEandP, 'MPNUM', len('MPNUM'))
INUM_HandEandP  = get_HandEandPforEntbase(MPNUM_HandEandP, 'INUM', len('INUM'))
FSTINUM_HandEandP  = get_HandEandPforEntbase(INUM_HandEandP, 'FSTINUM', len('FSTINUM'))
RGYEAR_HandEandP = get_HandEandPforEntbase(FSTINUM_HandEandP, 'RGYEAR', len('RGYEAR'))

#new_entbase2 = FSTINUM_HandE.copy()
new_entbase2 = RGYEAR_HandEandP.copy()

In [579]:
new_entbase2.shape

(436798, 259)

ver3.6

In [580]:
entbaseDAE = new_entbase2.copy()

In [581]:
entbaseDAE

,PROV,EID,RGYEAR,HY,ZCZB,ETYPE,MPNUM,INUM,ENUM,FINZB,...,RGYEAR_PROVandETYPE_median,RGYEAR_PROVandETYPE_max,RGYEAR_PROVandETYPE_mean,RGYEAR_PROVandHYandETYPE_median,RGYEAR_PROVandHYandETYPE_max,RGYEAR_PROVandHYandETYPE_mean,RGYEAR_PROV_gap,RGYEAR_PROVandHY_gap,RGYEAR_PROVandETYPE_gap,RGYEAR_PROVandHYandETYPE_gap
0,11,p13836,1980,51.0,480.0,13,25.0,1.0,1.0,98041.0000,...,1992,2015,1991.951526,1990.0,2013,1990.233846,-30.517320,-31.074920,-11.951526,-10.233846
1,11,p49137,1993,74.0,30.0,13,0.0,1.0,1.0,570.0000,...,1992,2015,1991.951526,1994.0,2015,1995.777778,-17.517320,-17.339322,1.048474,-2.777778
2,11,p108756,2015,69.0,1000.0,6,2.0,1.0,1.0,1000.0000,...,2013,2015,2010.969033,2014.0,2015,2014.189591,4.482680,1.092655,4.030967,0.810409
3,11,p7320,2005,74.0,240.0,5,0.0,2.0,2.0,1500.0000,...,2007,2015,2005.810045,2010.0,2015,2008.422222,-5.517320,-5.339322,-0.810045,-3.422222
4,11,p194070,2014,51.0,100000.0,3,3.0,2.0,2.0,1000.0000,...,2010,2015,2007.657556,2006.0,2015,2006.250000,3.482680,2.925080,6.342444,7.750000
5,11,p120116,2009,51.0,800.0,6,3.0,1.0,1.0,5000.0000,...,2013,2015,2010.969033,2013.0,2015,2011.358401,-1.517320,-2.074920,-1.969033,-2.358401
6,11,p197225,2011,75.0,3000.0,6,4.0,8.0,1.0,10500.0000,...,2013,2015,2010.969033,2010.0,2015,2009.810354,0.482680,0.031959,0.030967,1.189646
7,11,p60345,1995,54.0,14200.0,5,0.0,2.0,2.0,11280.0000,...,2007,2015,2005.810045,1996.0,2015,1995.432692,-15.517320,-13.901329,-10.810045,-0.432692
8,11,p124661,2002,48.0,2800.0,7,0.0,22.0,4.0,100.0000,...,2013,2015,2011.236393,2013.0,2015,2011.465116,-8.517320,-8.059871,-9.236393,-9.465116
9,11,p107376,2004,51.0,50.0,6,0.0,2.0,2.0,100.0000,...,2013,2015,2010.969033,2013.0,2015,2011.358401,-6.517320,-7.074920,-6.969033,-7.358401
10,11,p154162,1982,55.0,1000.0,6,9.0,2.0,2.0,619318.0000,...,2013,2015,2010.969033,2011.0,2015,2007.657895,-28.517320,-22.787879,-28.969033,-25.657895
11,11,p8549,2015,51.0,7000.0,6,3.0,2.0,2.0,909980.0000,...,2013,2015,2010.969033,2013.0,2015,2011.358401,4.482680,3.925080,4.030967,3.641599
12,11,p2642,2013,51.0,510.0,6,0.0,2.0,1.0,1100.0000,...,2013,2015,2010.969033,2013.0,2015,2011.358401,2.482680,1.925080,2.030967,1.641599
13,11,p167536,2013,52.0,100.0,6,7.0,1.0,1.0,5590.0000,...,2013,2015,2010.969033,2013.0,2015,2012.685671,2.482680,1.497978,2.030967,0.314329
14,11,p77869,2011,72.0,1000.0,6,5.0,2.0,2.0,2000.0000,...,2013,2015,2010.969033,2013.0,2015,2011.158985,0.482680,-0.291085,0.030967,-0.158985
15,11,p167465,2012,51.0,50.0,6,1.0,1.0,1.0,3529.4118,...,2013,2015,2010.969033,2013.0,2015,2011.358401,1.482680,0.925080,1.030967,0.641599
16,11,p34337,1991,25.0,6800.0,5,0.0,2.0,2.0,8000.0000,...,2007,2015,2005.810045,1998.0,2005,1998.000000,-19.517320,-13.862069,-14.810045,-7.000000
17,11,p224672,2013,51.0,40000.0,16,0.0,4.0,3.0,40000.0000,...,2013,2015,2010.780684,2012.0,2015,2009.260870,2.482680,1.925080,2.219316,3.739130
18,11,p210667,2013,65.0,10.0,6,9.0,2.0,1.0,1319.3483,...,2013,2015,2010.969033,2014.0,2015,2011.597206,2.482680,1.593167,2.030967,1.402794
19,11,p29109,1986,53.0,150.0,17,4.0,1.0,1.0,13000.0000,...,1993,2015,1993.280252,1986.0,2013,1994.666667,-24.517320,-22.380952,-7.280252,-8.666667
20,11,p72115,2004,51.0,500.0,6,3.0,1.0,1.0,3000.0000,...,2013,2015,2010.969033,2013.0,2015,2011.358401,-6.517320,-7.074920,-6.969033,-7.358401
21,11,p159540,2010,70.0,2000.0,6,25.0,3.0,2.0,24250.0000,...,2013,2015,2010.969033,2010.0,2015,2008.747994,-0.517320,1.320931,-0.969033,1.252006
22,11,p226334,2015,58.0,1000.0,6,15.0,2.0,2.0,200000.0000,...,2013,2015,2010.969033,2011.0,2015,2009.838340,4.482680,4.613894,4.030967,5.161660
23,11,p225,2012,41.0,300.0,6,2.0,1.0,1.0,1000.0000,...,2013,2015,2010.969033,2013.0,2015,2011.583851,1.482680,0.357793,1.030967,0.416149
24,11,p164048,2015,60.0,500.0,6,3.0,2.0,1.0,2000.0000,...,2013,2015,2010.969033,2014.0,2015,2011.784483,4.482680,2.779851,4.030967,3.215517
25,11,p157646,2014,81.0,10.0,6,1.0,2.0,1.0,549.3298,...,2013,2015,2010.969033,2014.0,2015,2013.361321,3.482680,1.798221,3.030967,0.638679
26,11,p132503,2010,72.0,10100.0,16,0.0,2.0,2.0,10000.0000,...,2013,2015,2010.780684,2014.0,2015,2013.016189,-0.517320,-1.291085,-0.780684,-3.016189
27,11,p23164,2014,40.0,500.0,6,9.0,2.0,2.0,3811.1600,...,2013,2015,2010.969033,2009.0,2015,2007.672414,3.482680,6.941043,3.030967,6.327586
28,11,p45370,1992,38.0,2800.0,5,4.0,3.0,3.0,200.0000,...,2007,2015,2005.810045,2004.0,2015,2003.617978,-18.517320,-17.193069,-13.810045,-11.617978
29,11,p84560,1989,54.0,100.0,6,2.0,2.0,2.0,269.2000,...,2013,2015,2010.969033,2009.0,2015,2008.514831,-21.517320,-19.901329,-21.969033,-19.514831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436768,12,s64628,2012,75.0,10.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,2.515231,2.144608,1.775104,1.759885
436769,12,s438115,2010,52.0,50.0,7,4.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,0.515231,-0.394611,-0.224896,-1.029407
436770,12,s166272,2013,75.0,100.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,3.515231,3.144608,2.775104,2.759885
436771,12,s155027,2012,51.0,200.0,7,1.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,2.515231,2.746081,1.775104,1.992568
436772,12,s367365,2012,51.0,110.0,7,1.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,2.515231,2.746081,1.775104,1.992568
436773,12,s138462,2015,51.0,300.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,5.515231,5.746081,4.775104,4.992568
436774,12,s319387,2013,75.0,200.0,7,0.0,4.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,3.515231,3.144608,2.775104,2.759885
436775,12,s298513,2007,75.0,300.0,7,1.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,-2.484769,-2.855392,-3.224896,-3.240115
436776,12,s486365,2012,51.0,100.0,16,0.0,22.0,1.0,0.0000,...,2014,2015,2012.453229,2008.5,2015,2007.947368,2.515231,2.746081,-0.453229,4.052632
436777,12,s163049,2015,51.0,50.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,5.515231,5.746081,4.775104,4.992568
436778,12,s464886,2000,75.0,2100.0,7,4.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,-9.484769,-9.855392,-10.224896,-10.240115
436779,12,s437336,2007,75.0,100.0,6,0.0,1.0,1.0,0.0000,...,2010,2015,2007.915366,2011.0,2015,2008.881897,-2.484769,-2.855392,-0.915366,-1.881897
436780,12,s55914,2014,52.0,10.0,7,5.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,4.515231,3.605389,3.775104,2.970593
436781,12,s246522,2004,72.0,2500.0,7,2.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2010.655068,-5.484769,-6.403102,-6.224896,-6.655068
436782,12,s383445,1999,52.0,30.0,7,1.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,-10.484769,-11.394611,-11.224896,-12.029407
436783,12,s235758,2007,74.0,50.0,7,1.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.296968,-2.484769,-2.633379,-3.224896,-3.296968
436784,12,s260705,2003,51.0,50.0,7,0.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,-6.484769,-6.253919,-7.224896,-7.007432
436785,12,s29540,2013,70.0,1100.0,7,4.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2009.0,2015,2008.539426,3.515231,6.015968,2.775104,4.460574
436786,12,s513207,2009,65.0,5000.0,3,1.0,2.0,0.0,0.0000,...,2012,2015,2009.258294,2009.5,2015,2008.547619,-0.484769,-0.871587,-0.258294,0.452381
436787,12,s493526,2010,52.0,10.0,7,0.0,3.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,0.515231,-0.394611,-0.224896,-1.029407
436788,12,s232439,2006,75.0,3.0,8,0.0,1.0,0.0,0.0000,...,2009,2015,2008.647317,2008.0,2015,2008.134130,-3.484769,-3.855392,-2.647317,-2.134130
436789,12,s243096,2015,87.0,50.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.047037,5.515231,4.274015,4.775104,3.952963
436790,12,s461479,2010,51.0,100.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,0.515231,0.746081,-0.224896,-0.007432
436791,12,s242382,2013,51.0,500.0,7,1.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.007432,3.515231,3.746081,2.775104,2.992568
436792,12,s440160,2013,52.0,100.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,3.515231,2.605389,2.775104,1.970593
436793,12,s143196,2015,75.0,10.0,7,2.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2011.0,2015,2010.240115,5.515231,5.144608,4.775104,4.759885
436794,12,s429712,2014,52.0,100.0,7,2.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,4.515231,3.605389,3.775104,2.970593
436795,12,s5937,2013,59.0,500.0,7,0.0,4.0,0.0,0.0000,...,2011,2015,2010.224896,2010.0,2015,2009.521293,3.515231,4.063588,2.775104,3.478707
436796,12,s262843,2012,59.0,10.0,7,2.0,2.0,0.0,0.0000,...,2011,2015,2010.224896,2010.0,2015,2009.521293,2.515231,3.063588,1.775104,2.478707
436797,12,s175584,2014,52.0,100.0,7,0.0,1.0,0.0,0.0000,...,2011,2015,2010.224896,2012.0,2015,2011.029407,4.515231,3.605389,3.775104,2.970593

In [582]:
train1 = pd.merge(new_train, entbaseDAE, on = 'EID', how = 'left')
test1 = pd.merge(test, entbaseDAE, on = 'EID', how = 'left')

# Alter Feature

In [583]:
alter = pd.read_csv(data_path + '2alter.csv')

In [584]:
alter

            EID ALTERNO  ALTDATE  ALTBE   ALTAF
0            p2      01  2015-01    NaN     NaN
1            p2      04  2015-01    NaN     NaN
2            p2      10  2015-01    NaN     NaN
3            p2      12  2014-08    NaN     NaN
4            p2      12  2015-01    NaN     NaN
5           p11      13  2014-07    NaN     NaN
6           p13      03  2015-05    NaN     NaN
7           p17      13  2014-04    NaN     NaN
8           p17      12  2014-04    NaN     NaN
9           p23      12  2015-08    NaN     NaN
10          p24      13  2015-03    NaN     NaN
11          p24      10  2015-08    NaN     NaN
12          p32      12  2014-09    NaN     NaN
13          p32      03  2014-09    NaN     NaN
14          p32      10  2014-09    NaN     NaN
15          p34      01  2014-07    NaN     NaN
16          p37      13  2014-12    NaN     NaN
17          p44      12  2014-09    NaN     NaN
18          p44      10  2014-09    NaN     NaN
19          p44      03  2014-09    NaN     NaN
20          p47      13  2015-04    NaN     NaN
21          p47      05  2015-07  100.0  1000.0
22          p50      10  2014-09    NaN     NaN
23          p50      13  2014-09    NaN     NaN
24          p50      12  2014-09    NaN     NaN
25          p50      05  2014-09   50.0   200.0
26          p52      13  2014-03    NaN     NaN
27          p53      05  2015-01   10.0  1200.0
28          p53      12  2015-01    NaN     NaN
29          p54      13  2015-01    NaN     NaN
...         ...     ...      ...    ...     ...
398208   s37171      02  2014-10    NaN     NaN
398209   s37171      99  2014-02    NaN     NaN
398210   s37171      02  2014-10    NaN     NaN
398211  s260279      02  2015-08    NaN     NaN
398212  s260279      02  2015-08    NaN     NaN
398213  s170391      03  2014-12    NaN     NaN
398214  s170391      03  2015-07    NaN     NaN
398215  s170391   A_015  2015-03    NaN     NaN
398216  s170391   A_015  2015-07    NaN     NaN
398217  s170391   A_015  2015-05    NaN     NaN
398218   s48285      05  2015-08   10.0    50.0
398219   s48285      10  2015-08    NaN     NaN
398220   s48285      12  2015-08    NaN     NaN
398221   s48285   A_015  2015-08    NaN     NaN
398222   s48285      01  2015-08    NaN     NaN
398223   s48285      03  2015-08    NaN     NaN
398224   s48285      04  2015-08    NaN     NaN
398225   s48285      12  2015-03    NaN     NaN
398226  s168878      12  2013-12    NaN     NaN
398227  s168878      02  2015-01    NaN     NaN
398228  s246202      99  2014-01    NaN     NaN
398229  s418064      05  2015-04  100.0   500.0
398230  s418064      12  2015-04    NaN     NaN
398231  s234153      99  2014-01    NaN     NaN
398232  s503274   A_015  2013-12    NaN     NaN
398233  s503274   A_015  2013-10    NaN     NaN
398234  s503274      03  2013-12    NaN     NaN
398235  s394824      12  2015-02    NaN     NaN
398236   s35089      10  2014-02    NaN     NaN
398237   s35089   A_015  2014-02    NaN     NaN

[398238 rows x 5 columns]

In [585]:
alter.ALTERNO.unique()

array(['01', '04', '10', '12', '13', '03', '05', '02', '99', '27', 'A_015',
       '14'], dtype=object)

In [586]:
alter.ALTDATE.unique()

array(['2015-01', '2014-08', '2014-07', '2015-05', '2014-04', '2015-08',
       '2015-03', '2014-09', '2014-12', '2015-04', '2015-07', '2014-03',
       '2014-10', '2014-05', '2014-11', '2014-06', '2015-02', '2015-06',
       '2014-02', '2013-11', '2013-09', '2013-12', '2014-01', '2013-10'], dtype=object)

In [587]:
import re

In [588]:
from sklearn import preprocessing  

cdf = alter.copy()
label_enc = preprocessing.LabelEncoder()
label_enc.fit(alter.ALTERNO.values)
cdf.ALTERNO = label_enc.transform(alter.ALTERNO.values)
alterno_05, alterno_27 = label_enc.transform(['05', '27']) 
cdf['ALTDATE_LE'] = label_enc.fit_transform(alter.ALTDATE.values)
cdf['ALTDATE'] = cdf['ALTDATE'].apply(translateYear)

new_df = cdf.groupby(['EID'], as_index = 0)['ALTERNO'].count()
new_df.columns = ['EID', 'ALT_NUM']
ALTNO_VC = cdf.groupby(['EID'])['ALTERNO'].value_counts().unstack().fillna(0).add_prefix('ALTERNO_').reset_index()

In [589]:
cdf

            EID  ALTERNO  ALTDATE  ALTBE   ALTAF  ALTDATE_LE
0            p2        0        1    NaN     NaN          16
1            p2        3        1    NaN     NaN          16
2            p2        5        1    NaN     NaN          16
3            p2        6       -4    NaN     NaN          11
4            p2        6        1    NaN     NaN          16
5           p11        7       -5    NaN     NaN          10
6           p13        2        5    NaN     NaN          20
7           p17        7       -8    NaN     NaN           7
8           p17        6       -8    NaN     NaN           7
9           p23        6        8    NaN     NaN          23
10          p24        7        3    NaN     NaN          18
11          p24        5        8    NaN     NaN          23
12          p32        6       -3    NaN     NaN          12
13          p32        2       -3    NaN     NaN          12
14          p32        5       -3    NaN     NaN          12
15          p34        0       -5    NaN     NaN          10
16          p37        7        0    NaN     NaN          15
17          p44        6       -3    NaN     NaN          12
18          p44        5       -3    NaN     NaN          12
19          p44        2       -3    NaN     NaN          12
20          p47        7        4    NaN     NaN          19
21          p47        4        7  100.0  1000.0          22
22          p50        5       -3    NaN     NaN          12
23          p50        7       -3    NaN     NaN          12
24          p50        6       -3    NaN     NaN          12
25          p50        4       -3   50.0   200.0          12
26          p52        7       -9    NaN     NaN           6
27          p53        4        1   10.0  1200.0          16
28          p53        6        1    NaN     NaN          16
29          p54        7        1    NaN     NaN          16
...         ...      ...      ...    ...     ...         ...
398208   s37171        1       -2    NaN     NaN          13
398209   s37171       10      -10    NaN     NaN           5
398210   s37171        1       -2    NaN     NaN          13
398211  s260279        1        8    NaN     NaN          23
398212  s260279        1        8    NaN     NaN          23
398213  s170391        2        0    NaN     NaN          15
398214  s170391        2        7    NaN     NaN          22
398215  s170391       11        3    NaN     NaN          18
398216  s170391       11        7    NaN     NaN          22
398217  s170391       11        5    NaN     NaN          20
398218   s48285        4        8   10.0    50.0          23
398219   s48285        5        8    NaN     NaN          23
398220   s48285        6        8    NaN     NaN          23
398221   s48285       11        8    NaN     NaN          23
398222   s48285        0        8    NaN     NaN          23
398223   s48285        2        8    NaN     NaN          23
398224   s48285        3        8    NaN     NaN          23
398225   s48285        6        3    NaN     NaN          18
398226  s168878        6      -12    NaN     NaN           3
398227  s168878        1        1    NaN     NaN          16
398228  s246202       10      -11    NaN     NaN           4
398229  s418064        4        4  100.0   500.0          19
398230  s418064        6        4    NaN     NaN          19
398231  s234153       10      -11    NaN     NaN           4
398232  s503274       11      -12    NaN     NaN           3
398233  s503274       11      -14    NaN     NaN           1
398234  s503274        2      -12    NaN     NaN           3
398235  s394824        6        2    NaN     NaN          17
398236   s35089        5      -10    NaN     NaN           5
398237   s35089       11      -10    NaN     NaN           5

[398238 rows x 6 columns]

In [590]:
# 12.4 alterno label feature
tmp = cdf.copy()

tmp_train = pd.merge(train[['TARGET', 'EID']], cdf[['ALTERNO','EID']], on = 'EID', how = 'left')
tmp_train.fillna(-1, inplace = True)

count_alter_label = tmp_train.groupby(['TARGET','ALTERNO']).count().reset_index()
alterno_label_0 = count_alter_label[count_alter_label.TARGET == 0]
alterno_label_1 = count_alter_label[count_alter_label.TARGET == 1]
alterno_label_0.rename(columns = {'EID': 'ALTERNO_label_0_count'},inplace = True)
alterno_label_1.rename(columns = {'EID': 'ALTERNO_label_1_count'},inplace = True)


alterno_label_count = pd.merge(alterno_label_0, alterno_label_1, on = 'ALTERNO', how = 'left')
alterno_label_count.drop(['TARGET_x', 'TARGET_y'], axis = 1, inplace = True)

alterno_label_count

def get_AlTERNO_LogOdds(row):
    label_0 = row.ALTERNO_label_0_count
    label_1 = row.ALTERNO_label_1_count
    all_count = label_0 + label_1
    c = 0.01
    logOdds = math.log(label_0 + c * label_0 / all_count) - math.log(label_1 + c * label_1 / all_count)
    return logOdds

alterno_label_count['ALTERNO_label_LogOdds'] = alterno_label_count.apply(get_AlTERNO_LogOdds, axis = 1)
alterno_label_count['ALTERNO_label_1_rate'] = alterno_label_count['ALTERNO_label_1_count'] * 1.0 / (alterno_label_count['ALTERNO_label_1_count']+ alterno_label_count['ALTERNO_label_0_count'])

/opt/anaconda/lib/python3.6/site-packages/pandas/core/frame.py:2746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [591]:
alterno_label_count

,ALTERNO,ALTERNO_label_0_count,ALTERNO_label_1_count,ALTERNO_label_LogOdds,ALTERNO_label_1_rate
0,-1.0,128590,21752,1.776923,0.144683
1,0.0,7524,1744,1.461917,0.188174
2,1.0,15666,2289,1.923378,0.127485
3,2.0,18125,4057,1.496848,0.182896
4,3.0,7217,1541,1.544008,0.175953
5,4.0,16158,2409,1.903204,0.129746
6,5.0,23668,4308,1.703650,0.153989
7,6.0,38617,5535,1.942601,0.125362
8,7.0,3476,402,2.157185,0.103662
9,8.0,394,41,2.262779,0.094253
10,9.0,3522,455,2.046487,0.114408
11,10.0,16788,2645,1.847993,0.136109
12,11.0,19048,3880,1.591127,0.169225

ALTNO 
05, 27

In [592]:
cdf['ALTGAP'] = cdf.ALTAF - cdf.ALTBE
cdf_05 = cdf[cdf.ALTERNO == alterno_05]
cdf_27 = cdf[cdf.ALTERNO == alterno_27]

In [593]:
cdf_05

            EID  ALTERNO  ALTDATE    ALTBE      ALTAF  ALTDATE_LE     ALTGAP
21          p47        4        7   100.00  1000.0000          22   900.0000
25          p50        4       -3    50.00   200.0000          12   150.0000
27          p53        4        1    10.00  1200.0000          16  1190.0000
47          p77        4        7    10.00   300.0000          22   290.0000
51          p89        4        3   100.00   500.0000          18   400.0000
54          p92        4       -1    50.00   500.0000          14   450.0000
67         p104        4       -2    10.00    50.0000          13    40.0000
69         p108        4       -3    50.00   800.0000          12   750.0000
76         p131        4        1    50.00   300.0000          16   250.0000
81         p132        4       -6    50.00   100.0000           9    50.0000
96         p141        4        1    10.00   100.0000          16    90.0000
101        p143        4        2    10.00   200.0000          17   190.0000
115        p168        4       -1     3.00    15.0000          14    12.0000
143        p237        4       -5     3.00    50.0000          10    47.0000
147        p237        4        7    50.00   500.0000          22   450.0000
149        p240        4       -9    10.00   200.0000           6   190.0000
159        p260        4       -8    50.00   200.0000           7   150.0000
161        p263        4       -1    10.00  1000.0000          14   990.0000
163        p270        4        8     3.00    10.0000          23     7.0000
167        p279        4        3    50.00   500.0000          18   450.0000
169        p284        4       -7   800.00  1100.0000           8   300.0000
177        p301        4        2    30.00   100.0000          17    70.0000
180        p302        4       -4    50.00   850.0000          11   800.0000
184        p302        4       -1   850.00   500.0000          14  -350.0000
186        p302        4        0   500.00  3088.0000          15  2588.0000
195        p305        4        5     3.00   100.0000          20    97.0000
204        p317        4        1     3.00   100.0000          16    97.0000
225        p394        4       -6     3.00   100.0000           9    97.0000
241        p412        4       -3    50.00   200.0000          12   150.0000
270        p471        4        4     5.00    50.0000          19    45.0000
...         ...      ...      ...      ...        ...         ...        ...
397974  s130774        4      -11    50.00   200.0000           4   150.0000
397976  s437118        4       -2   130.00   330.0000          13   200.0000
397996  s431088        4        3    30.00  1250.0000          18  1220.0000
397999  s499426        4       -8    50.00    80.0000           7    30.0000
398002  s273994        4       -8    30.00   100.0000           7    70.0000
398007  s499172        4      -10    10.00    20.0000           5    10.0000
398015  s361210        4        4    10.00   500.0000          19   490.0000
398024  s370120        4       -1    20.00   200.0000          14   180.0000
398032  s254273        4        8    43.75    50.0000          23     6.2500
398034  s254273        4        5    30.00    43.7500          20    13.7500
398036  s180664        4        7    10.00    50.0000          22    40.0000
398046  s252312        4        4    10.00   100.0000          19    90.0000
398059  s485035        4        0  2500.00  3200.0000          15   700.0000
398060  s485035        4       -9  2300.00  2500.0000           6   200.0000
398065   s36207        4        0    10.00   500.0000          15   490.0000
398070  s330870        4        0   100.00   500.0000          15   400.0000
398074  s102743        4      -12   300.00   500.0000           3   200.0000
398091  s525405        4       -9    10.00    50.0000           6    40.0000
398098  s149978        4       -3    10.00   100.0000          12    90.0000
398101   s19894        4       -9    10.00   510.0000           6   500.0000
398104   s19894        4       -9    10.00   510.0000           6   500.0000
398114  s343232        4       -1    50.00   100.0000          14    50.0000
398117  s343232        4       -1    50.00   100.0000          14    50.0000
398118  s343232        4       -1    50.00   100.0000          14    50.0000
398121   s43672        4        4   300.00   315.7895          19    15.7895
398145  s278981        4       -1    50.00   400.0000          14   350.0000
398150  s165731        4      -15  1000.00   696.0000           0  -304.0000
398202  s117344        4       -9   300.00   500.0000           6   200.0000
398218   s48285        4        8    10.00    50.0000          23    40.0000
398229  s418064        4        4   100.00   500.0000          19   400.0000

[37330 rows x 7 columns]

In [594]:
#version 2.2     ver4.1  add sum
cdf_05_be = cdf_05.groupby(['EID'])['ALTBE'].agg([sum, max, min, np.mean])
cdf_05_af = cdf_05.groupby(['EID'])['ALTAF'].agg([sum, max, min, np.mean])
cdf_27_be = cdf_27.groupby(['EID'])['ALTBE'].agg([sum, max, min, np.mean])
cdf_27_af = cdf_27.groupby(['EID'])['ALTAF'].agg([sum, max, min, np.mean])

cdf_05_count = cdf_05.groupby(['EID'])['ALTERNO'].count()
cdf_27_count = cdf_27.groupby(['EID'])['ALTERNO'].count()

In [595]:
#ver4.2  add range
cdf_05_be['range'] = cdf_05_be['max'] - cdf_05_be['min']
cdf_05_af['range'] = cdf_05_af['max'] - cdf_05_af['min']
cdf_27_be['range'] = cdf_27_be['max'] - cdf_27_be['min']
cdf_27_af['range'] = cdf_05_be['max'] - cdf_27_af['min']

In [596]:
cdf_05_be = cdf_05_be.add_prefix('ALTNO_05_BE_').reset_index()
cdf_05_af = cdf_05_af.add_prefix('ALTNO_05_AF_').reset_index()
cdf_27_be = cdf_27_be.add_prefix('ALTNO_27_BE_').reset_index()
cdf_27_af = cdf_27_af.add_prefix('ALTNO_27_AF_').reset_index()
cdf_05_count = cdf_05_count.reset_index().rename(columns = {'ALTERNO': 'ALTNO_05_Count'})
cdf_27_count = cdf_27_count.reset_index().rename(columns = {'ALTERNO': 'ALTNO_27_Count'})

In [597]:
new_df1 = pd.merge(new_df, ALTNO_VC, on = 'EID', how = 'left')
new_df2 = pd.merge(new_df1, cdf_05_be, on = 'EID', how = 'left')
new_df3 = pd.merge(new_df2, cdf_05_af, on = 'EID', how = 'left')
new_df4 = pd.merge(new_df3, cdf_27_be, on = 'EID', how = 'left')
new_df5 = pd.merge(new_df4, cdf_27_af, on = 'EID', how = 'left')
new_df6 = pd.merge(new_df5, cdf_05_count, on = 'EID', how = 'left')
new_df7 = pd.merge(new_df6, cdf_27_count, on = 'EID', how = 'left')

In [598]:
new_df7

,EID,ALT_NUM,ALTERNO_0,ALTERNO_1,ALTERNO_2,ALTERNO_3,ALTERNO_4,ALTERNO_5,ALTERNO_6,ALTERNO_7,...,ALTNO_27_BE_min,ALTNO_27_BE_mean,ALTNO_27_BE_range,ALTNO_27_AF_sum,ALTNO_27_AF_max,ALTNO_27_AF_min,ALTNO_27_AF_mean,ALTNO_27_AF_range,ALTNO_05_Count,ALTNO_27_Count
0,p10000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,p100004,2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2,p100007,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,p100010,4,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,p100016,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
5,p100018,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,p100022,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
7,p100031,3,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
8,p100034,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,p100043,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
10,p100045,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,p100049,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,p10005,2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,p100054,3,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,p100057,2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
15,p100058,3,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,p100062,2,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,p100065,2,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,p100069,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,p100075,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,p100077,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,p100079,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,p100084,6,0.0,0.0,1.0,1.0,0.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,p100102,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,p100106,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,p10011,2,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
26,p100110,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,p100117,4,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,p100118,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,p100120,2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136004,s99836,2,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136005,s99840,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136006,s99842,3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136007,s99847,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136008,s99855,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136009,s9986,5,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
136010,s99861,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136011,s99865,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136012,s99869,12,1.0,0.0,2.0,1.0,1.0,2.0,1.0,0.0,...,3.0,3.0,0.0,10.0,10.0,10.0,10.0,0.0,1.0,1.0
136013,s99873,8,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
136014,s99876,3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136015,s99885,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
136016,s99886,4,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136017,s99889,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136018,s99892,3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136019,s99893,4,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136020,s99894,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136021,s99899,2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136022,s99904,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136023,s99914,4,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136024,s99916,3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,50.0,50.0,0.0,100.0,100.0,100.0,100.0,-50.0,1.0,1.0
136025,s99918,6,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136026,s99950,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136027,s99955,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136028,s99964,2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136029,s99965,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136030,s99972,8,1.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136031,s99979,2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136032,s99983,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136033,s99991,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN

version 2   (效果好)

In [599]:
# v1
"""
cdf_05_gap = cdf_05.groupby(['EID'])['ALTGAP'].agg({'max': np.max, 'min': np.min, 'mean': np.mean, 'median': np.median})
cdf_27_gap = cdf_27.groupby(['EID'])['ALTGAP'].agg({'max': np.max, 'min': np.min, 'mean': np.mean, 'median': np.median})"""
# version 2.2   v4  add sum
cdf_05_gap = cdf_05.groupby(['EID'])['ALTGAP'].agg([sum, max, min, np.mean])
cdf_27_gap = cdf_27.groupby(['EID'])['ALTGAP'].agg([sum, max, min, np.mean])

#v4.2  add range
cdf_05_gap['range'] = cdf_05_gap['max'] - cdf_05_gap['min']
cdf_27_gap['range'] = cdf_27_gap['max'] - cdf_27_gap['min']

cdf_05_gap = cdf_05_gap.add_prefix('ALTNO_05_GAP_').reset_index()
cdf_27_gap = cdf_27_gap.add_prefix('ALTNO_27_GAP_').reset_index()

new_df8 = pd.merge(new_df7, cdf_05_gap, on = 'EID', how = 'left')
new_df9 = pd.merge(new_df8, cdf_27_gap, on = 'EID', how = 'left')

# *** 
cdf2015 = cdf[cdf.ALTDATE >= 61]  # 61: 2015-01
cdf2015_alter_sum = cdf2015.groupby(['EID']).size().reset_index().rename(columns = {0: 'alter2015_sum'})

df_2015 = pd.merge(new_df, cdf2015_alter_sum, on='EID', how = 'left').fillna(0)
df_2015['alter2015_rate'] = df_2015['alter2015_sum'] / df_2015['ALT_NUM']
df_2015 = df_2015.drop(['ALT_NUM'], axis = 1)

new_df10 = pd.merge(new_df9, df_2015, on = 'EID', how = 'left')

v4.1

In [600]:
alter

            EID ALTERNO  ALTDATE  ALTBE   ALTAF
0            p2      01  2015-01    NaN     NaN
1            p2      04  2015-01    NaN     NaN
2            p2      10  2015-01    NaN     NaN
3            p2      12  2014-08    NaN     NaN
4            p2      12  2015-01    NaN     NaN
5           p11      13  2014-07    NaN     NaN
6           p13      03  2015-05    NaN     NaN
7           p17      13  2014-04    NaN     NaN
8           p17      12  2014-04    NaN     NaN
9           p23      12  2015-08    NaN     NaN
10          p24      13  2015-03    NaN     NaN
11          p24      10  2015-08    NaN     NaN
12          p32      12  2014-09    NaN     NaN
13          p32      03  2014-09    NaN     NaN
14          p32      10  2014-09    NaN     NaN
15          p34      01  2014-07    NaN     NaN
16          p37      13  2014-12    NaN     NaN
17          p44      12  2014-09    NaN     NaN
18          p44      10  2014-09    NaN     NaN
19          p44      03  2014-09    NaN     NaN
20          p47      13  2015-04    NaN     NaN
21          p47      05  2015-07  100.0  1000.0
22          p50      10  2014-09    NaN     NaN
23          p50      13  2014-09    NaN     NaN
24          p50      12  2014-09    NaN     NaN
25          p50      05  2014-09   50.0   200.0
26          p52      13  2014-03    NaN     NaN
27          p53      05  2015-01   10.0  1200.0
28          p53      12  2015-01    NaN     NaN
29          p54      13  2015-01    NaN     NaN
...         ...     ...      ...    ...     ...
398208   s37171      02  2014-10    NaN     NaN
398209   s37171      99  2014-02    NaN     NaN
398210   s37171      02  2014-10    NaN     NaN
398211  s260279      02  2015-08    NaN     NaN
398212  s260279      02  2015-08    NaN     NaN
398213  s170391      03  2014-12    NaN     NaN
398214  s170391      03  2015-07    NaN     NaN
398215  s170391   A_015  2015-03    NaN     NaN
398216  s170391   A_015  2015-07    NaN     NaN
398217  s170391   A_015  2015-05    NaN     NaN
398218   s48285      05  2015-08   10.0    50.0
398219   s48285      10  2015-08    NaN     NaN
398220   s48285      12  2015-08    NaN     NaN
398221   s48285   A_015  2015-08    NaN     NaN
398222   s48285      01  2015-08    NaN     NaN
398223   s48285      03  2015-08    NaN     NaN
398224   s48285      04  2015-08    NaN     NaN
398225   s48285      12  2015-03    NaN     NaN
398226  s168878      12  2013-12    NaN     NaN
398227  s168878      02  2015-01    NaN     NaN
398228  s246202      99  2014-01    NaN     NaN
398229  s418064      05  2015-04  100.0   500.0
398230  s418064      12  2015-04    NaN     NaN
398231  s234153      99  2014-01    NaN     NaN
398232  s503274   A_015  2013-12    NaN     NaN
398233  s503274   A_015  2013-10    NaN     NaN
398234  s503274      03  2013-12    NaN     NaN
398235  s394824      12  2015-02    NaN     NaN
398236   s35089      10  2014-02    NaN     NaN
398237   s35089   A_015  2014-02    NaN     NaN

[398238 rows x 5 columns]

In [601]:
# 计算最近两次更改的时间差  数值越小代表越频繁
eid_altdate_df = pd.read_csv(data_path + 'eid_alterdate_gap.csv')
new_df11 = pd.merge(new_df10, eid_altdate_df, on = 'EID', how = 'left')

v4.2

In [602]:
alter_date_sta = cdf.groupby(['EID'])['ALTDATE'].agg([max, min]).add_prefix('alter_ALTDATE_').reset_index()
alter_date_sta['alter_ALTDATE_range'] = alter_date_sta['alter_ALTDATE_max'] - alter_date_sta['alter_ALTDATE_min']
new_df12 = pd.merge(new_df11, alter_date_sta, on = 'EID', how = 'left')

In [603]:
# 12.4 alterno label feature
new_cdf = pd.merge(cdf, alterno_label_count, on = 'ALTERNO', how = 'left')
new_cdf.drop(['ALTERNO_label_0_count', 'ALTERNO_label_1_count'], axis = 1, inplace = True)

ALTERNO_avg_LogOdds = new_cdf.groupby(['EID'])['ALTERNO_label_LogOdds'].mean().reset_index()
ALTERNO_avg_label_1_rate = new_cdf.groupby(['EID'])['ALTERNO_label_1_rate'].mean().reset_index()

new_df13 = pd.merge(new_df12, ALTERNO_avg_LogOdds, on = 'EID', how ='left')
new_df14 = pd.merge(new_df13, ALTERNO_avg_label_1_rate, on = 'EID', how ='left')

In [604]:
alterDAE = new_df14.copy()

In [605]:
train2 = pd.merge(train1, alterDAE, on = 'EID', how = 'left')
test2 = pd.merge(test1, alterDAE, on = 'EID', how = 'left' )
train2.fillna(0, inplace = True)
test2.fillna(0, inplace = True)

# branch feature

In [606]:
branch = pd.read_csv(data_path + '3branch.csv')

In [607]:
branch

            EID   TYPECODE  IFHOME  B_REYEAR  B_ENDYEAR
0            p2   pbr32949       0      2008        NaN
1            p2   pbr28271       0      2004     2004.0
2            p2   pbr14086       0      2005     2008.0
3            p2    pbr9435       0      2010     2015.0
4           p56       pbr1       1      2011        NaN
5           p56   pbr18805       1      2012        NaN
6          p166   pbr18806       1      2015        NaN
7          p235   pbr32950       1      2008     2009.0
8          p572   pbr14087       1      2013        NaN
9          p572    pbr9436       1      2014     2015.0
10         p608       pbr2       1      2015        NaN
11         p608   pbr32951       0      2005        NaN
12         p608   pbr18807       1      1999     2014.0
13         p622       pbr3       1      2011     2013.0
14         p636    pbr4718       1      2003     2014.0
15         p636   pbr28272       1      2001     2012.0
16         p636   pbr28273       1      2000     2012.0
17         p636   pbr18808       1      2001     2006.0
18         p636   pbr28274       1      2002     2007.0
19         p653    pbr4719       1      2003     2006.0
20         p660   pbr28275       1      2001     2002.0
21         p686   pbr18809       1      2013        NaN
22         p690    pbr9437       1      2011     2015.0
23         p690    pbr4720       1      2005        NaN
24         p690    pbr9438       1      2015        NaN
25         p699    pbr9439       1      2014        NaN
26         p720   pbr32952       1      2009        NaN
27         p720       pbr4       1      2006     2008.0
28         p733   pbr28276       1      2006     2007.0
29         p744    pbr4721       1      2014        NaN
...         ...        ...     ...       ...        ...
164120  s514454  sbr240344       0      2010        NaN
164121  s283391  sbr240345       0      2008        NaN
164122  s514454  sbr240347       0      2013        NaN
164123  s359726  sbr240352       0      2014        NaN
164124  s104441  sbr240353       0      1994        NaN
164125  s509677  sbr240358       0      2008        NaN
164126  s406151  sbr240359       1      2001        NaN
164127  s452069  sbr240361       0      2014        NaN
164128  s514454  sbr240362       0      2008        NaN
164129  s308616  sbr240364       1      2004        NaN
164130  s360645  sbr240366       1      2011        NaN
164131  s147262  sbr240368       0      2013        NaN
164132  s514454  sbr240369       0      2011        NaN
164133  s104441  sbr240370       0      2005        NaN
164134  s514454  sbr240373       0      2008        NaN
164135  s514454  sbr240374       0      2011        NaN
164136  s514454  sbr240375       0      2008        NaN
164137  s514454  sbr240376       0      2008        NaN
164138  s283391  sbr240378       0      2008        NaN
164139  s514454  sbr240379       0      2010        NaN
164140  s104441  sbr240380       0      1998        NaN
164141  s109090  sbr240386       0      2010        NaN
164142  s514454  sbr240387       0      2010        NaN
164143  s514454  sbr240388       0      2014        NaN
164144  s514454  sbr240390       0      2008        NaN
164145  s514454  sbr240392       0      2008        NaN
164146   s94695  sbr240394       0      2010        NaN
164147  s104441  sbr240395       0      2005        NaN
164148  s174049  sbr240399       1      2009        NaN
164149  s108704  sbr240402       1      2012        NaN

[164150 rows x 5 columns]

In [608]:
# 关停的年份
branch.B_REYEAR.unique()

array([2008, 2004, 2005, 2010, 2011, 2012, 2015, 2013, 2014, 1999, 2003,
       2001, 2000, 2002, 2009, 2006, 1996, 1984, 1991, 2007, 1997, 1989,
       1998, 1986, 1985, 1992, 1993, 1995, 1994, 1988, 1990, 1987, 1982,
       1983, 1981, 1967, 1980, 1976, 1978, 1962, 1959, 1977, 1899, 1979,
       1900, 1974, 1969, 1973, 1975, 1950, 1955, 1972, 1956, 1965, 1964,
       1952, 1960, 1971, 1970, 1954, 1963, 1949, 1958])

In [609]:
# 关停的年份
branch.B_ENDYEAR.unique()

array([   nan,  2004.,  2008.,  2015.,  2009.,  2014.,  2013.,  2012.,
        2006.,  2007.,  2002.,  2005.,  2010.,  1997.,  2003.,  2011.,
        2000.,  1994.,  2001.,  1998.,  1996.,  1995.,  1999.,  1992.,
        1990.,  1987.,  1989.,  1993.,  1991.,  1986.,  1950.,  1988.,
        1985.,  1899.,  1949.,  1900.])

In [610]:
# 439公司有315家分公司记录
branch[branch.EID == 439]

Empty DataFrame
Columns: [EID, TYPECODE, IFHOME, B_REYEAR, B_ENDYEAR]
Index: []

In [611]:
branch['TYPECODE'] = branch['TYPECODE'].apply(lambda row: row[2:])

In [612]:
len(branch.EID.unique())

27736

In [613]:
new_branch = branch.groupby(['EID'])['IFHOME'].count()
new_branch = new_branch.reset_index().rename(columns = {'IFHOME': "Branch_Count"})

bstart_count = branch.groupby(['EID'])['B_REYEAR'].count().reset_index().rename(columns = {'B_REYEAR': "Bstart_count"})
bend_count = branch[branch.B_ENDYEAR.isnull() == False].groupby(['EID'])['B_ENDYEAR'].count().reset_index().rename(columns = {'B_ENDYEAR': 'Bend_count'})
bhome_count = branch.groupby(['EID', 'IFHOME'])['TYPECODE'].count().unstack().add_prefix('BRANCH_IFHOME_').add_suffix('_count').reset_index()

new_branch1 = pd.merge(new_branch, bstart_count, on = 'EID', how = 'left')
new_branch2 = pd.merge(new_branch1, bend_count, on = 'EID', how = 'left')
new_branch3 = pd.merge(new_branch2, bhome_count, on = 'EID', how = 'left')

new_branch3['BRANCH_IFHOME_0_rate'] = new_branch3['BRANCH_IFHOME_0_count'] / new_branch3['Branch_Count']
new_branch3['BRANCH_IFHOME_1_rate'] = new_branch3['BRANCH_IFHOME_1_count'] / new_branch3['Branch_Count']
new_branch3['Bend_rate'] = new_branch3['Bend_count'] / new_branch3['Branch_Count']

In [614]:
new_branch

           EID  Branch_Count
0      p100035             1
1      p100037             1
2      p100118             2
3      p100164            19
4      p100187             7
5      p100205             1
6      p100206             2
7      p100230             1
8      p100266             1
9      p100304             1
10     p100306             2
11     p100339             1
12      p10034             1
13     p100348             2
14     p100360             1
15     p100368             1
16     p100392             1
17     p100410             3
18     p100411             1
19     p100434             3
20     p100435             1
21     p100471             1
22     p100533             2
23     p100571             1
24     p100625             3
25     p100676             2
26     p100711             2
27     p100766             1
28     p100789             2
29     p100801             1
...        ...           ...
27706    s9917             1
27707   s99233             1
27708   s99297             1
27709   s99304             1
27710   s99326             3
27711    s9933             1
27712   s99346             1
27713   s99377             1
27714   s99405             3
27715   s99424             2
27716   s99466            33
27717   s99538             1
27718   s99569             2
27719    s9957             2
27720   s99574             3
27721   s99583             1
27722   s99607             1
27723    s9962             2
27724   s99637             1
27725   s99678             1
27726   s99680             1
27727   s99687             2
27728   s99775             1
27729   s99795             1
27730   s99819            21
27731   s99830             1
27732   s99840             1
27733   s99893             1
27734   s99906             1
27735   s99920             1

[27736 rows x 2 columns]

version2 (有效)

In [615]:
#**
branch_start_2013 = branch[branch.B_REYEAR >= 2013].groupby(['EID']).size().reset_index().rename(columns = {0 : 'branch_start_from2013_count'})
branch_end_2013 = branch[branch.B_ENDYEAR >= 2013].groupby(['EID']).size().reset_index().rename(columns = {0 : 'branch_end_from2013_count'})

new_branch4 = pd.merge(new_branch3, branch_start_2013, on = 'EID', how = 'left')
new_branch5 = pd.merge(new_branch4, branch_end_2013, on = 'EID', how = 'left')

new_branch5.fillna(0, inplace = True)

version3

In [616]:
last_branch = branch[branch.B_ENDYEAR.isnull()]['B_REYEAR'].groupby(branch.EID).max().reset_index()
new_branch6 = pd.merge(new_branch5, last_branch, on = 'EID', how = 'left')

new_branch6.fillna(-1, inplace = True)

ver4.2

In [617]:
B_REYEAR_sta = branch['B_REYEAR'].groupby(branch.EID).agg([max, min])
B_REYEAR_sta['range'] = B_REYEAR_sta['max'] - B_REYEAR_sta['min']
B_REYEAR_sta = B_REYEAR_sta.add_prefix('branch_B_REYEAR_').reset_index()

B_ENDYEAR_sta = branch['B_ENDYEAR'].groupby(branch.EID).agg([max, min])
B_ENDYEAR_sta['range'] = B_ENDYEAR_sta['max'] - B_ENDYEAR_sta['min']
B_ENDYEAR_sta = B_ENDYEAR_sta.add_prefix('branch_B_ENDYEAR_').reset_index()

new_branch7 = pd.merge(new_branch6, B_REYEAR_sta, on = 'EID', how = 'left')
new_branch8 = pd.merge(new_branch7, B_ENDYEAR_sta, on = 'EID', how = 'left')

In [618]:
new_branch8

,EID,Branch_Count,Bstart_count,Bend_count,BRANCH_IFHOME_0_count,BRANCH_IFHOME_1_count,BRANCH_IFHOME_0_rate,BRANCH_IFHOME_1_rate,Bend_rate,branch_start_from2013_count,branch_end_from2013_count,B_REYEAR,branch_B_REYEAR_max,branch_B_REYEAR_min,branch_B_REYEAR_range,branch_B_ENDYEAR_max,branch_B_ENDYEAR_min,branch_B_ENDYEAR_range
0,p100035,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2014.0,2014,2014,0,NaN,NaN,NaN
1,p100037,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
2,p100118,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,0.0,2008.0,2008,2008,0,2011.0,2011.0,0.0
3,p100164,19,19,1.0,0.0,19.0,0.000000,1.000000,0.052632,11.0,1.0,2015.0,2015,2010,5,2015.0,2015.0,0.0
4,p100187,7,7,0.0,0.0,7.0,0.000000,1.000000,0.000000,7.0,0.0,2014.0,2014,2013,1,NaN,NaN,NaN
5,p100205,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN
6,p100206,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2012,3,NaN,NaN,NaN
7,p100230,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2012.0,2012.0,0.0
8,p100266,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2008,2008,0,2011.0,2011.0,0.0
9,p100304,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2009,2009,0,2009.0,2009.0,0.0
10,p100306,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2002,3,NaN,NaN,NaN
11,p100339,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2006.0,2006.0,0.0
12,p10034,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2010.0,2010,2010,0,NaN,NaN,NaN
13,p100348,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,2.0,0.0,2015.0,2015,2013,2,NaN,NaN,NaN
14,p100360,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2008,2008,0,2009.0,2009.0,0.0
15,p100368,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
16,p100392,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2005,0,NaN,NaN,NaN
17,p100410,3,3,3.0,0.0,3.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,1989,1989,0,2002.0,2002.0,0.0
18,p100411,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2007.0,2007,2007,0,NaN,NaN,NaN
19,p100434,3,3,0.0,0.0,3.0,0.000000,1.000000,0.000000,1.0,0.0,2014.0,2014,2012,2,NaN,NaN,NaN
20,p100435,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2006.0,2006,2006,0,NaN,NaN,NaN
21,p100471,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2010.0,2010.0,0.0
22,p100533,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,1.0,2006.0,2007,2006,1,2013.0,2013.0,0.0
23,p100571,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2005,0,NaN,NaN,NaN
24,p100625,3,3,2.0,0.0,3.0,0.000000,1.000000,0.666667,1.0,1.0,2013.0,2013,2006,7,2013.0,2007.0,6.0
25,p100676,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2007,2005,2,2008.0,2006.0,2.0
26,p100711,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27,p100766,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,1.0,-1.0,2012,2012,0,2014.0,2014.0,0.0
28,p100789,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2007,2003,4,2012.0,2012.0,0.0
29,p100801,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2011,2011,0,2012.0,2012.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27706,s9917,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2011.0,2011,2011,0,NaN,NaN,NaN
27707,s99233,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27708,s99297,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2005,2005,0,2007.0,2007.0,0.0
27709,s99304,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27710,s99326,3,3,2.0,3.0,0.0,1.000000,0.000000,0.666667,1.0,0.0,2015.0,2015,2002,13,2007.0,2006.0,1.0
27711,s9933,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2004,2004,0,2006.0,2006.0,0.0
27712,s99346,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27713,s99377,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27714,s99405,3,3,1.0,0.0,3.0,0.000000,1.000000,0.333333,0.0,0.0,2010.0,2010,2003,7,2008.0,2008.0,0.0
27715,s99424,2,2,1.0,1.0,1.0,0.500000,0.500000,0.500000,0.0,0.0,2002.0,2004,2002,2,2006.0,2006.0,0.0
27716,s99466,33,33,11.0,31.0,2.0,0.939394,0.060606,0.333333,5.0,1.0,2015.0,2015,1993,22,2014.0,2003.0,11.0
27717,s99538,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN
27718,s99569,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27719,s9957,2,2,1.0,2.0,0.0,1.000000,0.000000,0.500000,1.0,0.0,2014.0,2014,2010,4,2012.0,2012.0,0.0
27720,s99574,3,3,2.0,3.0,0.0,1.000000,0.000000,0.666667,0.0,0.0,2010.0,2011,2010,1,2012.0,2012.0,0.0
27721,s99583,1,1,1.0,1.0,0.0,1.000000,0.000000,1.000000,0.0,0.0,-1.0,2005,2005,0,2005.0,2005.0,0.0
27722,s99607,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,0.0,0.0,2007.0,2007,2007,0,NaN,NaN,NaN
27723,s9962,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,0.0,2002.0,2002,2002,0,2007.0,2007.0,0.0
27724,s99637,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27725,s99678,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,0.0,0.0,2011.0,2011,2011,0,NaN,NaN,NaN
27726,s99680,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2010.0,2010,2010,0,NaN,NaN,NaN
27727,s99687,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,2.0,2.0,-1.0,2015,2014,1,2015.0,2015.0,0.0
27728,s99775,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27729,s99795,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2014.0,2014,2014,0,NaN,NaN,NaN
27730,s99819,21,21,6.0,21.0,0.0,1.000000,0.000000,0.285714,3.0,1.0,2015.0,2015,2000,15,2013.0,2005.0,8.0
27731,s99830,1,1,1.0,1.0,0.0,1.000000,0.000000,1.000000,0.0,1.0,-1.0,2011,2011,0,2013.0,2013.0,0.0
27732,s99840,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2001.0,2001,2001,0,NaN,NaN,NaN
27733,s99893,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2003.0,2003,2003,0,NaN,NaN,NaN
27734,s99906,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27735,s99920,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN

In [619]:
branchDAE = new_branch8.copy()

In [620]:
train3 = pd.merge(train2, branchDAE, on = 'EID', how = 'left')
test3 = pd.merge(test2, branchDAE, on = 'EID', how = 'left')

In [621]:
branchDAE

,EID,Branch_Count,Bstart_count,Bend_count,BRANCH_IFHOME_0_count,BRANCH_IFHOME_1_count,BRANCH_IFHOME_0_rate,BRANCH_IFHOME_1_rate,Bend_rate,branch_start_from2013_count,branch_end_from2013_count,B_REYEAR,branch_B_REYEAR_max,branch_B_REYEAR_min,branch_B_REYEAR_range,branch_B_ENDYEAR_max,branch_B_ENDYEAR_min,branch_B_ENDYEAR_range
0,p100035,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2014.0,2014,2014,0,NaN,NaN,NaN
1,p100037,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
2,p100118,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,0.0,2008.0,2008,2008,0,2011.0,2011.0,0.0
3,p100164,19,19,1.0,0.0,19.0,0.000000,1.000000,0.052632,11.0,1.0,2015.0,2015,2010,5,2015.0,2015.0,0.0
4,p100187,7,7,0.0,0.0,7.0,0.000000,1.000000,0.000000,7.0,0.0,2014.0,2014,2013,1,NaN,NaN,NaN
5,p100205,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN
6,p100206,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2012,3,NaN,NaN,NaN
7,p100230,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2012.0,2012.0,0.0
8,p100266,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2008,2008,0,2011.0,2011.0,0.0
9,p100304,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2009,2009,0,2009.0,2009.0,0.0
10,p100306,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2002,3,NaN,NaN,NaN
11,p100339,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2006.0,2006.0,0.0
12,p10034,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2010.0,2010,2010,0,NaN,NaN,NaN
13,p100348,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,2.0,0.0,2015.0,2015,2013,2,NaN,NaN,NaN
14,p100360,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2008,2008,0,2009.0,2009.0,0.0
15,p100368,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
16,p100392,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2005,0,NaN,NaN,NaN
17,p100410,3,3,3.0,0.0,3.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,1989,1989,0,2002.0,2002.0,0.0
18,p100411,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2007.0,2007,2007,0,NaN,NaN,NaN
19,p100434,3,3,0.0,0.0,3.0,0.000000,1.000000,0.000000,1.0,0.0,2014.0,2014,2012,2,NaN,NaN,NaN
20,p100435,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2006.0,2006,2006,0,NaN,NaN,NaN
21,p100471,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2006,2006,0,2010.0,2010.0,0.0
22,p100533,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,1.0,2006.0,2007,2006,1,2013.0,2013.0,0.0
23,p100571,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2005.0,2005,2005,0,NaN,NaN,NaN
24,p100625,3,3,2.0,0.0,3.0,0.000000,1.000000,0.666667,1.0,1.0,2013.0,2013,2006,7,2013.0,2007.0,6.0
25,p100676,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2007,2005,2,2008.0,2006.0,2.0
26,p100711,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27,p100766,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,1.0,-1.0,2012,2012,0,2014.0,2014.0,0.0
28,p100789,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2007,2003,4,2012.0,2012.0,0.0
29,p100801,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2011,2011,0,2012.0,2012.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27706,s9917,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2011.0,2011,2011,0,NaN,NaN,NaN
27707,s99233,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27708,s99297,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2005,2005,0,2007.0,2007.0,0.0
27709,s99304,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27710,s99326,3,3,2.0,3.0,0.0,1.000000,0.000000,0.666667,1.0,0.0,2015.0,2015,2002,13,2007.0,2006.0,1.0
27711,s9933,1,1,1.0,0.0,1.0,0.000000,1.000000,1.000000,0.0,0.0,-1.0,2004,2004,0,2006.0,2006.0,0.0
27712,s99346,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27713,s99377,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27714,s99405,3,3,1.0,0.0,3.0,0.000000,1.000000,0.333333,0.0,0.0,2010.0,2010,2003,7,2008.0,2008.0,0.0
27715,s99424,2,2,1.0,1.0,1.0,0.500000,0.500000,0.500000,0.0,0.0,2002.0,2004,2002,2,2006.0,2006.0,0.0
27716,s99466,33,33,11.0,31.0,2.0,0.939394,0.060606,0.333333,5.0,1.0,2015.0,2015,1993,22,2014.0,2003.0,11.0
27717,s99538,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN
27718,s99569,2,2,0.0,0.0,2.0,0.000000,1.000000,0.000000,0.0,0.0,2009.0,2009,2009,0,NaN,NaN,NaN
27719,s9957,2,2,1.0,2.0,0.0,1.000000,0.000000,0.500000,1.0,0.0,2014.0,2014,2010,4,2012.0,2012.0,0.0
27720,s99574,3,3,2.0,3.0,0.0,1.000000,0.000000,0.666667,0.0,0.0,2010.0,2011,2010,1,2012.0,2012.0,0.0
27721,s99583,1,1,1.0,1.0,0.0,1.000000,0.000000,1.000000,0.0,0.0,-1.0,2005,2005,0,2005.0,2005.0,0.0
27722,s99607,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,0.0,0.0,2007.0,2007,2007,0,NaN,NaN,NaN
27723,s9962,2,2,1.0,0.0,2.0,0.000000,1.000000,0.500000,0.0,0.0,2002.0,2002,2002,0,2007.0,2007.0,0.0
27724,s99637,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27725,s99678,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,0.0,0.0,2011.0,2011,2011,0,NaN,NaN,NaN
27726,s99680,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2010.0,2010,2010,0,NaN,NaN,NaN
27727,s99687,2,2,2.0,0.0,2.0,0.000000,1.000000,1.000000,2.0,2.0,-1.0,2015,2014,1,2015.0,2015.0,0.0
27728,s99775,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2013.0,2013,2013,0,NaN,NaN,NaN
27729,s99795,1,1,0.0,1.0,0.0,1.000000,0.000000,0.000000,1.0,0.0,2014.0,2014,2014,0,NaN,NaN,NaN
27730,s99819,21,21,6.0,21.0,0.0,1.000000,0.000000,0.285714,3.0,1.0,2015.0,2015,2000,15,2013.0,2005.0,8.0
27731,s99830,1,1,1.0,1.0,0.0,1.000000,0.000000,1.000000,0.0,1.0,-1.0,2011,2011,0,2013.0,2013.0,0.0
27732,s99840,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2001.0,2001,2001,0,NaN,NaN,NaN
27733,s99893,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2003.0,2003,2003,0,NaN,NaN,NaN
27734,s99906,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,1.0,0.0,2015.0,2015,2015,0,NaN,NaN,NaN
27735,s99920,1,1,0.0,0.0,1.0,0.000000,1.000000,0.000000,0.0,0.0,2008.0,2008,2008,0,NaN,NaN,NaN

# Invest Feature

In [622]:
invest = pd.read_csv(data_path + '4invest.csv')

In [623]:
invest

           EID    BTEID  IFHOME   BTBL  BTYEAR  BTENDYEAR
0       p17402  s102046       0  0.343    2012        NaN
1       p89336  s140778       0  1.000    2012        NaN
2      p142507   s62517       0  1.000    2011        NaN
3      p218390  s305106       0  0.800    2015        NaN
4      p134285  s425895       0  0.011    2014        NaN
5      p101545  s437754       0  1.000    2015        NaN
6       p17402  s107413       0  0.250    2015        NaN
7      p144466   s80568       0  0.630    1999        NaN
8      p150675  s521154       0  0.200    2013        NaN
9       p60187  s343826       0  0.500    2014        NaN
10     p228756   s23819       0  0.510    2007        NaN
11      p24806  s155434       0  0.800    2006        NaN
12      p75009  s150143       0  0.550    2015        NaN
13     p157346  s249252       0  0.090    2015        NaN
14     p132897  s442871       0  0.013    2012        NaN
15     p185920  s449650       0  1.000    1996        NaN
16     p117618  s223107       0  0.200    1998        NaN
17     p177842  s327136       0  1.000    2014        NaN
18      p89336  s289259       0  1.000    2012        NaN
19      p56705  s525363       0  0.058    2012        NaN
20     p159372  s358702       0  0.040    2014        NaN
21      p92288  s468208       0  0.074    2005        NaN
22      p40019  s410398       0  0.250    2015        NaN
23     p132897  s513752       0  0.067    2013        NaN
24     p137503  s336245       0  0.500    2013        NaN
25      p69153  s176163       0  1.000    2010        NaN
26     p115225  s476217       0  0.230    2000        NaN
27      p85952  s247425       0  0.300    1994        NaN
28     p181313  s400027       0  0.909    2015        NaN
29     p155878  s402724       0  0.333    2015        NaN
...        ...      ...     ...    ...     ...        ...
84159  s519739  w177738       0  0.800    2003        NaN
84160  s155954  w177747       0  1.000    2009        NaN
84161  s382126  w177749       0  0.060    2015        NaN
84162  s298829  w177750       0  0.990    2012        NaN
84163   s69829  w177752       1  0.250    2012        NaN
84164  s273262  w177754       0  0.400    2010        NaN
84165  s283903  w177756       0  0.300    2015        NaN
84166  s182394  w177759       1  0.280    2011        NaN
84167  s121572  w177761       0  0.083    2014        NaN
84168   s33484  w177762       0  1.000    2008     2015.0
84169  s235391  w177764       0  0.510    2015        NaN
84170   s94217  w177766       0  0.850    2012        NaN
84171  s509068  w177772       0  0.209    2009        NaN
84172   s87121  w177774       0  0.900    2010        NaN
84173  s348307  w177779       0  1.000    2006     2012.0
84174   s39948  w177784       1  0.200    2009        NaN
84175  s515622  w177790       1  0.900    2011        NaN
84176  s222787  w177792       0  1.000    2011        NaN
84177  s114354  w177794       1  1.000    2015        NaN
84178  s430578  w177798       0  1.000    2013        NaN
84179  s424682  w177805       1  0.045    2013        NaN
84180  s198966  w177810       0  0.990    2011        NaN
84181  s426644  w177811       1  0.350    2004     2007.0
84182  s511082  w177813       1  0.500    2012        NaN
84183   s23361  w177822       1  0.490    2013        NaN
84184  s295995  w177834       1  1.000    2012        NaN
84185  s446363  w177843       1  1.000    2013        NaN
84186  s394082  w177847       0  1.000    2008        NaN
84187  s487780  w177849       0  1.000    2015        NaN
84188  s191458  w177850       1  0.441    2007        NaN

[84189 rows x 6 columns]

In [624]:
new_invest = invest.groupby(['EID']).size().reset_index().rename(columns = {0: 'invest_count'})
invest_home = invest.groupby(['EID', 'IFHOME'])['BTEID'].count().unstack().add_prefix('INVEST_IFHOME_').add_suffix('_count').reset_index()
#be_invested_count = invest.groupby(['BTEID']).size().reset_index().rename(columns = {0: 'be_invested_count', 'BTEID': 'EID'})
#be_invested_home = invest.groupby(['BTEID', 'IFHOME'])['EID'].count().unstack().add_prefix('BE_INVESTED_IFHOME_').add_suffix('_count').reset_index().rename(columns = {'BTEID': 'EID'})
invest_btbl = invest.groupby(['EID'])['BTBL'].agg([sum, max, min, np.mean, np.median]).add_prefix('invest_btbl_').reset_index()
invest_closed = invest[invest.BTENDYEAR.isnull() == False].groupby(['EID']).size().reset_index().rename(columns = {0: 'invest_closed_count'})

new_invest1 = pd.merge(new_invest, invest_home, on = 'EID', how = 'left')
new_invest4 = pd.merge(new_invest1, invest_btbl, on = 'EID', how = 'left')
new_invest5 = pd.merge(new_invest4, invest_closed, on = 'EID', how = 'left')

new_invest5['INVEST_IFHOME_0_rate'] = new_invest5['INVEST_IFHOME_0_count'] / new_invest5['invest_count']
new_invest5['INVEST_IFHOME_1_rate'] = new_invest5['INVEST_IFHOME_1_count'] / new_invest5['invest_count']
new_invest5['invest_closed_rate'] = new_invest5['invest_closed_count'] / new_invest5['invest_count']

new_invest5.fillna(0, inplace = True)

version 2 .1

In [625]:
#*
invest_2014_not_end = invest[invest.BTENDYEAR.isnull()]
invest_after_2014 = invest_2014_not_end[invest_2014_not_end.BTYEAR > 2014]
invest_after_2014_count = invest_after_2014.groupby(['EID']).size().reset_index().rename(columns = {0: 'invest_from2014_count'})
invest_btbl_after2014 = invest_after_2014.groupby(['EID'])['BTBL'].agg([max, min, np.mean]).add_prefix('invest_btbl_after_2014_').reset_index()

#**
invest_before_2008 = invest[invest.BTYEAR < 2008]
invest_before_2008_count = invest_before_2008.groupby(['EID']).size().reset_index().rename(columns = {0: 'invest_before2008_count'})
invest_btbl_before2008 = invest_before_2008.groupby(['EID'])['BTBL'].agg([max, min, np.mean]).add_prefix('invest_btbl_before_2008_').reset_index()


new_invest6 = pd.merge(new_invest5, invest_after_2014_count, on = 'EID', how = 'left')
new_invest7 = pd.merge(new_invest6, invest_btbl_after2014, on = 'EID', how = 'left')
new_invest8 = pd.merge(new_invest7, invest_before_2008_count, on = 'EID', how = 'left')
new_invest9 = pd.merge(new_invest8, invest_btbl_before2008, on = 'EID', how = 'left')

new_invest9.fillna(0, inplace = True)

version 3.3

In [626]:
investDAE = new_invest9.copy()

In [627]:
investDAE

,EID,invest_count,INVEST_IFHOME_0_count,INVEST_IFHOME_1_count,invest_btbl_sum,invest_btbl_max,invest_btbl_min,invest_btbl_mean,invest_btbl_median,invest_closed_count,...,INVEST_IFHOME_1_rate,invest_closed_rate,invest_from2014_count,invest_btbl_after_2014_max,invest_btbl_after_2014_min,invest_btbl_after_2014_mean,invest_before2008_count,invest_btbl_before_2008_max,invest_btbl_before_2008_min,invest_btbl_before_2008_mean
0,p100164,4,0.0,4.0,4.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,4.0,1.000,1.000,1.000,0.0,0.000,0.000,0.000000
1,p100184,1,0.0,1.0,0.033,0.033,0.033,0.033000,0.0330,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
2,p10019,5,2.0,3.0,4.100,1.000,0.500,0.820000,1.0000,0.0,...,0.600000,0.000000,1.0,0.600,0.600,0.600,0.0,0.000,0.000,0.000000
3,p100206,2,0.0,2.0,1.341,1.000,0.341,0.670500,0.6705,1.0,...,1.000000,0.500000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
4,p100217,1,0.0,1.0,0.225,0.225,0.225,0.225000,0.2250,0.0,...,1.000000,0.000000,1.0,0.225,0.225,0.225,0.0,0.000,0.000,0.000000
5,p100220,3,0.0,3.0,0.887,0.490,0.007,0.295667,0.3900,1.0,...,1.000000,0.333333,0.0,0.000,0.000,0.000,2.0,0.490,0.390,0.440000
6,p100234,2,0.0,2.0,1.000,0.500,0.500,0.500000,0.5000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,2.0,0.500,0.500,0.500000
7,p100271,1,0.0,1.0,0.150,0.150,0.150,0.150000,0.1500,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
8,p100283,3,0.0,3.0,1.537,0.517,0.510,0.512333,0.5100,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
9,p100286,1,0.0,1.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
10,p10029,1,0.0,1.0,0.950,0.950,0.950,0.950000,0.9500,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
11,p100297,1,0.0,1.0,0.490,0.490,0.490,0.490000,0.4900,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
12,p100299,1,0.0,1.0,0.500,0.500,0.500,0.500000,0.5000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.500,0.500,0.500000
13,p100309,2,0.0,2.0,0.650,0.350,0.300,0.325000,0.3250,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.300,0.300,0.300000
14,p100327,2,0.0,2.0,1.100,0.900,0.200,0.550000,0.5500,0.0,...,1.000000,0.000000,1.0,0.200,0.200,0.200,0.0,0.000,0.000,0.000000
15,p100359,1,0.0,1.0,0.005,0.005,0.005,0.005000,0.0050,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
16,p100360,1,1.0,0.0,0.100,0.100,0.100,0.100000,0.1000,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.100,0.100,0.100000
17,p100373,1,0.0,1.0,0.500,0.500,0.500,0.500000,0.5000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
18,p100383,1,0.0,1.0,0.465,0.465,0.465,0.465000,0.4650,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.465,0.465,0.465000
19,p100405,1,0.0,1.0,0.016,0.016,0.016,0.016000,0.0160,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
20,p100457,1,0.0,1.0,0.750,0.750,0.750,0.750000,0.7500,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.750,0.750,0.750000
21,p100481,1,0.0,1.0,0.600,0.600,0.600,0.600000,0.6000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.600,0.600,0.600000
22,p100541,2,0.0,2.0,0.705,0.500,0.205,0.352500,0.3525,1.0,...,1.000000,0.500000,0.0,0.000,0.000,0.000,2.0,0.500,0.205,0.352500
23,p100565,1,0.0,1.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
24,p100571,1,0.0,1.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
25,p100580,2,0.0,2.0,2.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
26,p100626,2,1.0,1.0,1.490,1.000,0.490,0.745000,0.7450,0.0,...,0.500000,0.000000,2.0,1.000,0.490,0.745,0.0,0.000,0.000,0.000000
27,p100627,3,0.0,3.0,0.386,0.285,0.040,0.128667,0.0610,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.040,0.040,0.040000
28,p10064,2,0.0,2.0,1.034,0.524,0.510,0.517000,0.5170,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
29,p100642,3,0.0,3.0,2.600,1.000,0.800,0.866667,0.8000,1.0,...,1.000000,0.333333,0.0,0.000,0.000,0.000,2.0,1.000,0.800,0.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30698,s99233,1,0.0,1.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30699,s99243,1,0.0,1.0,0.333,0.333,0.333,0.333000,0.3330,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30700,s99251,3,0.0,3.0,1.710,0.900,0.010,0.570000,0.8000,1.0,...,1.000000,0.333333,0.0,0.000,0.000,0.000,2.0,0.900,0.800,0.850000
30701,s99253,2,0.0,2.0,1.000,0.500,0.500,0.500000,0.5000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30702,s99316,1,0.0,1.0,0.475,0.475,0.475,0.475000,0.4750,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30703,s99324,1,0.0,1.0,0.231,0.231,0.231,0.231000,0.2310,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30704,s99326,1,1.0,0.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,0.000000,0.000000,1.0,1.000,1.000,1.000,0.0,0.000,0.000,0.000000
30705,s99330,1,1.0,0.0,0.052,0.052,0.052,0.052000,0.0520,1.0,...,0.000000,1.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30706,s99354,1,0.0,1.0,0.750,0.750,0.750,0.750000,0.7500,0.0,...,1.000000,0.000000,1.0,0.750,0.750,0.750,0.0,0.000,0.000,0.000000
30707,s99386,7,5.0,2.0,5.638,1.000,0.478,0.805429,0.9500,1.0,...,0.285714,0.142857,1.0,0.510,0.510,0.510,0.0,0.000,0.000,0.000000
30708,s99415,2,2.0,0.0,1.500,1.000,0.500,0.750000,0.7500,1.0,...,0.000000,0.500000,1.0,0.500,0.500,0.500,0.0,0.000,0.000,0.000000
30709,s99424,1,0.0,1.0,0.600,0.600,0.600,0.600000,0.6000,1.0,...,1.000000,1.000000,0.0,0.000,0.000,0.000,1.0,0.600,0.600,0.600000
30710,s99434,1,0.0,1.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30711,s99465,1,1.0,0.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30712,s99466,13,8.0,5.0,10.860,1.000,0.200,0.835385,1.0000,2.0,...,0.384615,0.153846,2.0,1.000,0.500,0.750,10.0,1.000,0.200,0.836000
30713,s99478,1,0.0,1.0,0.500,0.500,0.500,0.500000,0.5000,1.0,...,1.000000,1.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30714,s99499,1,0.0,1.0,0.500,0.500,0.500,0.500000,0.5000,0.0,...,1.000000,0.000000,1.0,0.500,0.500,0.500,0.0,0.000,0.000,0.000000
30715,s99502,13,2.0,11.0,9.222,1.000,0.354,0.709385,0.7250,1.0,...,0.846154,0.076923,0.0,0.000,0.000,0.000,10.0,1.000,0.354,0.701200
30716,s99511,2,0.0,2.0,0.867,0.534,0.333,0.433500,0.4335,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,2.0,0.534,0.333,0.433500
30717,s99532,1,1.0,0.0,1.000,1.000,1.000,1.000000,1.0000,0.0,...,0.000000,0.000000,1.0,1.000,1.000,1.000,0.0,0.000,0.000,0.000000
30718,s99567,2,2.0,0.0,2.000,1.000,1.000,1.000000,1.0000,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30719,s99605,1,1.0,0.0,0.900,0.900,0.900,0.900000,0.9000,0.0,...,0.000000,0.000000,1.0,0.900,0.900,0.900,0.0,0.000,0.000,0.000000
30720,s99677,1,1.0,0.0,0.900,0.900,0.900,0.900000,0.9000,1.0,...,0.000000,1.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30721,s99717,1,0.0,1.0,0.500,0.500,0.500,0.500000,0.5000,1.0,...,1.000000,1.000000,0.0,0.000,0.000,0.000,1.0,0.500,0.500,0.500000
30722,s99765,1,1.0,0.0,0.450,0.450,0.450,0.450000,0.4500,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30723,s99775,19,0.0,19.0,9.053,1.000,0.097,0.476474,0.3360,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,17.0,1.000,0.097,0.455471
30724,s99791,6,4.0,2.0,1.717,0.933,0.013,0.286167,0.1255,0.0,...,0.333333,0.000000,1.0,0.020,0.020,0.020,2.0,0.020,0.013,0.016500
30725,s99819,1,0.0,1.0,0.900,0.900,0.900,0.900000,0.9000,0.0,...,1.000000,0.000000,0.0,0.000,0.000,0.000,1.0,0.900,0.900,0.900000
30726,s99928,3,3.0,0.0,2.494,1.000,0.500,0.831333,0.9940,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000
30727,s99979,1,1.0,0.0,0.333,0.333,0.333,0.333000,0.3330,0.0,...,0.000000,0.000000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000000

In [628]:
train4 = pd.merge(train3, investDAE, on = 'EID', how = 'left')
test4 = pd.merge(test3, investDAE, on = 'EID', how = 'left')

# Right Feature

In [629]:
right = pd.read_csv(data_path + '5right.csv')

In [630]:

right.RIGHTTYPE.unique()

array([11, 12, 20, 30, 40, 50, 60])

In [631]:
right

            EID  RIGHTTYPE     TYPECODE  ASKDATE   FBDATE
0       s244862         11         pno1  2012-11      NaN
1       s398369         11         pno2  2009-11      NaN
2       s398369         12         pno2  2009-11  2011-12
3       s461088         11         pno2  2009-11      NaN
4       s461088         12         pno2  2009-11  2011-12
5       s198466         12         pno4  2010-02  2012-04
6       s198466         11         pno4  2010-02      NaN
7       s175206         20         pno5  2012-12  2013-06
8       s198466         12         pno6  2010-02  2012-04
9       s198466         11         pno6  2010-02      NaN
10      s452219         11         pno8  2013-12      NaN
11      s398369         20        pno11  2013-05  2013-10
12      s226938         12        pno12  2010-12  2012-09
13      s226938         11        pno12  2010-12      NaN
14       s61968         20        pno13  2009-03  2009-12
15      s298748         12        pno14  2003-05  2008-02
16      s298748         11        pno14  2003-05      NaN
17       s79470         11        pno17  2007-09      NaN
18       s79470         12        pno17  2007-09  2012-12
19      s113070         11        pno17  2007-09      NaN
20      s113070         12        pno17  2007-09  2012-12
21      s357469         20        pno18  2012-12  2013-07
22      s517917         11        pno19  2014-01      NaN
23       s64416         12        pno20  2009-03  2012-05
24       s64416         11        pno20  2009-03      NaN
25      s176182         20        pno24  2014-09  2015-01
26      s129387         11        pno26  2006-04      NaN
27      s129387         12        pno26  2006-04  2008-08
28      s189437         11        pno27  2011-12      NaN
29      s189437         12        pno27  2011-12  2015-06
...         ...        ...          ...      ...      ...
831127   p80338         60  GXB52431789  2015-04  2015-04
831128   p80338         60  GXB52431789  2015-04  2015-04
831129   p28762         60     37177080  2013-08  2013-08
831130  p126762         60  GXB53023813  2015-05  2015-05
831131  p126762         60  GXB53023813  2015-05  2015-05
831132   p81537         60     47831851  2014-07  2014-07
831133  p199314         60     49447990  2014-10  2014-10
831134   p93316         60     40876194  2014-03  2014-03
831135  p206365         60     49980207  2014-11  2014-11
831136   p15242         60     47044087  2014-06  2014-06
831137   p21487         60     34430567  2013-03  2013-03
831138   p54115         60     28227251  2012-04  2012-04
831139  p169727         60     24795501  2011-11  2011-11
831140  p191497         60     49002987  2014-09  2014-09
831141  p120219         60     39770957  2013-12  2013-12
831142  p142227         60     49879790  2014-11  2014-11
831143  p142227         60     49879790  2014-11  2014-11
831144   p32761         60     41387370  2014-04  2014-04
831145   p72281         60  GXB51392716  2015-02  2015-02
831146  p102733         60  GXB55331978  2015-07  2015-07
831147  p181466         60     28272692  2012-04  2012-04
831148  p222592         60     38672476  2013-11  2013-11
831149  p195248         60     41106070  2014-03  2014-03
831150   p19477         60  GXB56100862  2015-08  2015-08
831151  p223718         60     49874290  2014-11  2014-11
831152   p32880         60     23821376  2011-09  2011-09
831153  p149569         60  GXB55934321  2015-08  2015-08
831154  p136707         60     47243144  2014-06  2014-06
831155    p6779         60     35400424  2013-04  2013-04
831156   p27576         60  GXB55369268  2015-07  2015-07

[831157 rows x 5 columns]

In [632]:
# 12.5 righttype label feature
tmp = right.copy()

tmp_train = pd.merge(train[['TARGET', 'EID']], tmp[['RIGHTTYPE','EID']], on = 'EID', how = 'left')
tmp_train.fillna(-1, inplace = True)

count_right_label = tmp_train.groupby(['TARGET','RIGHTTYPE']).count().reset_index()
righttype_label_0 = count_right_label[count_right_label.TARGET == 0]
righttype_label_1 = count_right_label[count_right_label.TARGET == 1]
righttype_label_0.rename(columns = {'EID': 'RIGHTTYPE_label_0_count'},inplace = True)
righttype_label_1.rename(columns = {'EID': 'RIGHTTYPE_label_1_count'},inplace = True)

count_right_label

righttype_label_count = pd.merge(righttype_label_0, righttype_label_1, on = 'RIGHTTYPE', how = 'left')
righttype_label_count.drop(['TARGET_x', 'TARGET_y'], axis = 1, inplace = True)


def get_RIGHTTYPE_LogOdds(row):
    label_0 = row.RIGHTTYPE_label_0_count
    label_1 = row.RIGHTTYPE_label_1_count
    all_count = label_0 + label_1
    c = 0.01
    logOdds = math.log(label_0 + c * label_0 / all_count) - math.log(label_1 + c * label_1 / all_count)
    return logOdds

righttype_label_count['RIGHTTYPE_label_LogOdds'] = righttype_label_count.apply(get_RIGHTTYPE_LogOdds, axis = 1)
righttype_label_count['RIGHTTYPE_label_1_rate'] = righttype_label_count['RIGHTTYPE_label_1_count'] * 1.0 / (righttype_label_count['RIGHTTYPE_label_1_count']+ righttype_label_count['RIGHTTYPE_label_0_count'])

/opt/anaconda/lib/python3.6/site-packages/pandas/core/frame.py:2746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [633]:
right.FBDATE.unique()

array([nan, '2011-12', '2012-04', '2013-06', '2013-10', '2012-09',
       '2009-12', '2008-02', '2012-12', '2013-07', '2012-05', '2015-01',
       '2008-08', '2015-06', '2008-01', '2013-08', '2012-01', '2010-05',
       '2015-04', '2012-07', '2013-11', '2014-05', '2004-06', '2013-09',
       '2014-11', '2006-12', '2013-02', '2005-08', '2013-03', '2010-12',
       '2006-01', '2010-11', '2007-01', '2012-02', '2012-11', '2015-02',
       '2009-06', '2014-03', '2008-06', '2013-05', '2014-10', '2009-05',
       '2014-06', '2007-10', '2014-02', '2010-03', '2008-12', '2014-01',
       '2002-05', '2010-06', '2014-04', '2012-10', '2011-04', '2006-11',
       '2001-06', '2003-09', '2014-08', '2010-02', '2015-08', '2015-05',
       '2002-11', '2010-10', '2013-04', '2009-09', '2008-10', '2015-07',
       '2014-12', '2009-08', '2004-07', '2006-06', '2010-01', '2011-10',
       '2011-02', '2014-09', '2012-08', '2013-01', '2007-12', '2011-01',
       '2010-04', '2014-07', '2009-03', '2011-08', '2002-04', '2011-11',
       '2012-03', '2011-06', '2008-07', '2009-07', '2006-02', '2011-07',
       '2013-12', '2007-09', '2009-02', '2010-09', '2007-07', '2006-09',
       '2004-02', '2008-09', '2012-06', '2003-12', '2002-10', '2015-03',
       '1992-08', '2007-02', '2007-11', '1988-05', '2004-12', '2011-03',
       '2003-05', '2006-08', '2009-10', '2006-07', '2006-10', '2009-11',
       '2008-11', '2002-06', '2010-08', '2008-04', '2000-02', '2006-05',
       '2007-03', '1992-09', '2009-01', '2011-05', '2010-07', '2001-11',
       '2011-09', '2007-08', '2001-10', '2005-12', '2009-04', '2001-12',
       '2007-06', '2007-04', '2007-05', '2004-01', '1992-07', '2008-05',
       '2005-05', '1998-04', '2005-02', '2005-11', '2005-06', '2002-07',
       '2005-01', '1996-02', '2003-04', '2003-03', '2005-09', '2008-03',
       '1995-01', '1991-08', '1993-05', '1993-06', '2000-08', '2000-11',
       '2002-02', '2003-06', '1994-02', '1999-08', '1999-09', '2000-07',
       '2006-03', '1996-06', '2003-08', '2003-10', '2000-01', '1999-12',
       '2004-10', '2003-11', '1999-11', '2001-09', '2001-07', '2003-01',
       '2002-03', '2000-04', '2000-03', '2004-09', '2005-10', '2006-04',
       '2003-07', '2001-03', '2002-12', '2004-08', '2002-08', '1998-08',
       '1999-06', '2005-03', '1994-01', '2001-05', '1996-10', '2004-11',
       '1991-10', '2005-07', '2004-04', '2004-03', '1996-04', '1998-12',
       '1990-05', '1993-10', '1997-09', '1990-08', '2004-05', '1995-04',
       '2001-01', '2000-06', '2000-05', '2002-09', '2001-04', '2005-04',
       '1989-08', '1991-01', '2002-01', '1993-07', '2003-02', '1992-02',
       '2001-08', '1998-06', '1996-08', '2000-12', '1996-11', '1991-05',
       '1995-09', '2001-02', '1996-03', '1999-07', '1992-12', '1997-06',
       '1996-01', '1990-12', '2000-10', '1990-11', '1997-04', '1994-12',
       '1990-03', '1993-02', '1992-06', '1998-05', '1996-12', '1997-03',
       '1995-08', '1996-09', '1996-07', '1997-02', '1994-07', '1998-09',
       '1999-03', '1991-04', '1991-07', '1995-05', '1994-03', '1988-07',
       '1990-02', '1999-02', '1995-10', '1988-04', '1995-12', '1992-01',
       '1994-05', '1999-04', '1993-11', '1995-07', '2000-09', '1998-10',
       '1998-11', '1999-05', '1999-01', '1997-05', '1997-08', '1997-12',
       '1998-01', '1998-03', '1988-06', '1999-10', '1994-09', '1998-07',
       '1995-11', '1992-10', '1997-01', '1991-06', '1987-09', '1990-04',
       '1994-06', '1996-05', '1987-05', '1995-06', '1993-08', '1988-10',
       '1988-08', '1992-05', '1993-03', '1988-11', '1998-02', '1987-07',
       '1987-08', '1989-01', '1991-02', '1991-03', '1988-03', '1990-09',
       '1994-08', '1994-10', '1990-06', '1994-04', '1995-03', '1992-03',
       '1989-10', '1997-10', '1986-10', '1990-10', '1995-02', '1992-11',
       '1989-09', '1997-07', '1987-10', '1993-09', '1989-05', '1991-11',
       '1993-04', '1986-12', '1988-01', '1987-12', '1988-02', '1994-11',
       '1997-11', '1989-07', '1991-09', '1991-12', '1986-08', '1986-03',
       '1987-04', '1989-03', '1992-04', '1986-07', '1989-11', '1988-09',
       '1989-04', '1993-12', '1987-11', '1989-06', '1990-01', '1989-02',
       '1988-12', '1987-01', '2016-01', '2015-12', '2016-08', '2016-03',
       '2015-10', '2016-11', '2016-09', '2015-09', '2016-06', '2016-05',
       '2017-02', '2016-04', '2016-02', '2016-07', '2015-11', '2016-10',
       '2016-12', '2017-12', '2017-04', '2017-05', '1984-07', '2017-07',
       '1986-01', '2017-09', '2017-01', '2017-03', '2017-06', '2017-10',
       '2018-06', '2018-03', '2017-08', '2017-11', '2018-01', '1986-05',
       '2018-08', '2018-04', '2018-02', '1993-01', '1989-12', '1987-06',
       '1984-06', '1986-11', '1985-03', '1985-02', '1984-02', '1987-02',
       '1983-11', '1986-06', '1987-03', '1985-01', '1979-11', '1984-12',
       '2018-05', '1985-10', '1986-02', '1990-07', '1986-09', '1984-10',
       '1984-09', '1983-12', '1984-11', '1984-04', '1985-12', '1973-06',
       '2021-06', '1983-10', '1985-06'], dtype=object)

In [634]:
new_right = right.groupby(['EID']).size().reset_index().rename(columns = {0: 'right_count'})
right_type_count = right.groupby(['EID', 'RIGHTTYPE']).size().unstack().add_prefix('right_type_').add_suffix('_count').reset_index()

new_right1 = pd.merge(new_right, right_type_count, on = 'EID', how = 'left')

new_right1.fillna(0, inplace = True)

In [635]:
right

            EID  RIGHTTYPE     TYPECODE  ASKDATE   FBDATE
0       s244862         11         pno1  2012-11      NaN
1       s398369         11         pno2  2009-11      NaN
2       s398369         12         pno2  2009-11  2011-12
3       s461088         11         pno2  2009-11      NaN
4       s461088         12         pno2  2009-11  2011-12
5       s198466         12         pno4  2010-02  2012-04
6       s198466         11         pno4  2010-02      NaN
7       s175206         20         pno5  2012-12  2013-06
8       s198466         12         pno6  2010-02  2012-04
9       s198466         11         pno6  2010-02      NaN
10      s452219         11         pno8  2013-12      NaN
11      s398369         20        pno11  2013-05  2013-10
12      s226938         12        pno12  2010-12  2012-09
13      s226938         11        pno12  2010-12      NaN
14       s61968         20        pno13  2009-03  2009-12
15      s298748         12        pno14  2003-05  2008-02
16      s298748         11        pno14  2003-05      NaN
17       s79470         11        pno17  2007-09      NaN
18       s79470         12        pno17  2007-09  2012-12
19      s113070         11        pno17  2007-09      NaN
20      s113070         12        pno17  2007-09  2012-12
21      s357469         20        pno18  2012-12  2013-07
22      s517917         11        pno19  2014-01      NaN
23       s64416         12        pno20  2009-03  2012-05
24       s64416         11        pno20  2009-03      NaN
25      s176182         20        pno24  2014-09  2015-01
26      s129387         11        pno26  2006-04      NaN
27      s129387         12        pno26  2006-04  2008-08
28      s189437         11        pno27  2011-12      NaN
29      s189437         12        pno27  2011-12  2015-06
...         ...        ...          ...      ...      ...
831127   p80338         60  GXB52431789  2015-04  2015-04
831128   p80338         60  GXB52431789  2015-04  2015-04
831129   p28762         60     37177080  2013-08  2013-08
831130  p126762         60  GXB53023813  2015-05  2015-05
831131  p126762         60  GXB53023813  2015-05  2015-05
831132   p81537         60     47831851  2014-07  2014-07
831133  p199314         60     49447990  2014-10  2014-10
831134   p93316         60     40876194  2014-03  2014-03
831135  p206365         60     49980207  2014-11  2014-11
831136   p15242         60     47044087  2014-06  2014-06
831137   p21487         60     34430567  2013-03  2013-03
831138   p54115         60     28227251  2012-04  2012-04
831139  p169727         60     24795501  2011-11  2011-11
831140  p191497         60     49002987  2014-09  2014-09
831141  p120219         60     39770957  2013-12  2013-12
831142  p142227         60     49879790  2014-11  2014-11
831143  p142227         60     49879790  2014-11  2014-11
831144   p32761         60     41387370  2014-04  2014-04
831145   p72281         60  GXB51392716  2015-02  2015-02
831146  p102733         60  GXB55331978  2015-07  2015-07
831147  p181466         60     28272692  2012-04  2012-04
831148  p222592         60     38672476  2013-11  2013-11
831149  p195248         60     41106070  2014-03  2014-03
831150   p19477         60  GXB56100862  2015-08  2015-08
831151  p223718         60     49874290  2014-11  2014-11
831152   p32880         60     23821376  2011-09  2011-09
831153  p149569         60  GXB55934321  2015-08  2015-08
831154  p136707         60     47243144  2014-06  2014-06
831155    p6779         60     35400424  2013-04  2013-04
831156   p27576         60  GXB55369268  2015-07  2015-07

[831157 rows x 5 columns]

version 2.1

In [636]:
# ***
right_apply_after2013 = right[right.ASKDATE >= '2013-01']
right_apply_after2013_count = right_apply_after2013.groupby(['EID']).size().reset_index().rename(columns = {0: 'right_ask_after2013_count'})

# 筛选2013之后申请权利 且 获得权利的记录
right_get_after2013 = right_apply_after2013[right_apply_after2013.FBDATE.notnull()]
right_get_after2013_count = right_get_after2013.groupby(['EID']).size().reset_index().rename(columns = {0: 'right_get_after2013_count'})

right_after2013 = pd.merge(right_apply_after2013_count, right_get_after2013_count, on = 'EID', how = 'left')
right_after2013['right_get_after2013_rate'] = right_after2013['right_get_after2013_count'] / right_after2013['right_ask_after2013_count']

right_get_in2015_count = right[right.FBDATE >= '2015-01'].groupby(['EID']).size().reset_index().rename(columns = {0: 'right_get_in2015_count'})

new_right2 = pd.merge(new_right1, right_after2013, on = 'EID', how = 'left')
new_right3 = pd.merge(new_right2, right_get_in2015_count, on = 'EID', how = 'left')
new_right3.fillna(0, inplace = True)

v4.2

In [637]:
rightDATE = right[['EID']]
rightDATE['ASKDATE'] = right.ASKDATE.apply(translateYear)
rightDATE['FBDATE'] = right.FBDATE.apply(translateYear)

ASKDATE_sta = rightDATE['ASKDATE'].groupby(rightDATE.EID).agg([max, min])
ASKDATE_sta['range'] = ASKDATE_sta['max'] - ASKDATE_sta['min']
ASKDATE_sta = ASKDATE_sta.add_prefix('right_ASKDATE_').reset_index()

FBDATE_sta = rightDATE['FBDATE'].groupby(rightDATE.EID).agg([max, min])
FBDATE_sta['range'] = FBDATE_sta['max'] - FBDATE_sta['min']
FBDATE_sta = FBDATE_sta.add_prefix('right_FBDATE_').reset_index()

new_right4 = pd.merge(new_right3, ASKDATE_sta, on = 'EID', how = 'left')
new_right5 = pd.merge(new_right4, FBDATE_sta, on = 'EID', how = 'left')

/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [638]:
# 12.5 righttype label feature
"""new_cdf = pd.merge(right, righttype_label_count, on = 'RIGHTTYPE', how = 'left')
new_cdf.drop(['RIGHTTYPE_label_0_count', 'RIGHTTYPE_label_1_count'], axis = 1, inplace = True)

RIGHTTYPE_avg_LogOdds = new_cdf.groupby(['EID'])['RIGHTTYPE_label_LogOdds'].mean().reset_index()
RIGHTTYPE_avg_label_1_rate = new_cdf.groupby(['EID'])['RIGHTTYPE_label_1_rate'].mean().reset_index()

new_right6 = pd.merge(new_right5, RIGHTTYPE_avg_LogOdds, on = 'EID', how ='left')
new_right7 = pd.merge(new_right6, RIGHTTYPE_avg_label_1_rate, on = 'EID', how ='left')"""

"new_cdf = pd.merge(right, righttype_label_count, on = 'RIGHTTYPE', how = 'left')\nnew_cdf.drop(['RIGHTTYPE_label_0_count', 'RIGHTTYPE_label_1_count'], axis = 1, inplace = True)\n\nRIGHTTYPE_avg_LogOdds = new_cdf.groupby(['EID'])['RIGHTTYPE_label_LogOdds'].mean().reset_index()\nRIGHTTYPE_avg_label_1_rate = new_cdf.groupby(['EID'])['RIGHTTYPE_label_1_rate'].mean().reset_index()\n\nnew_right6 = pd.merge(new_right5, RIGHTTYPE_avg_LogOdds, on = 'EID', how ='left')\nnew_right7 = pd.merge(new_right6, RIGHTTYPE_avg_label_1_rate, on = 'EID', how ='left')"

In [639]:
rightDAE = new_right5.copy()

In [640]:
train5 = pd.merge(train4, rightDAE , on = 'EID', how = 'left')
test5 = pd.merge(test4, rightDAE , on = 'EID', how = 'left')

# Project Feature

In [641]:
project = pd.read_csv(data_path + '6project.csv')

In [642]:
project

           EID  TYPECODE   DJDATE  IFHOME
0      s172273   3156047  2013-11       1
1      s172273   4006392  2014-01       0
2      s172273   4833051  2014-12       1
3      s138582   4510345  2014-09       0
4      s372279   4636040  2014-10       0
5      s372279   4006095  2014-01       0
6       s11198   3984451  2014-01       0
7       s27847   4350599  2014-07       0
8      s506176   3068317  2013-10       1
9      s464937   4192469  2014-05       1
10     s209430   5019449  2015-02       1
11     s237658   5679446  2015-08       0
12     s237658   5773414  2015-08       0
13     s150432   4935068  2015-01       1
14     s150432   4249537  2014-06       0
15     s446280   3149388  2013-11       0
16     s446280   3138950  2013-11       0
17     s446280   5497572  2015-07       0
18     s415563   4906934  2015-01       1
19      s94607   4170338  2014-05       1
20      s94607   4177882  2014-05       1
21      s31283   5772055  2015-08       0
22     s207331   3032393  2013-09       0
23     s207331   4528526  2014-09       0
24     s207331   4510734  2014-09       0
25      s50183   4517423  2014-09       1
26     s331109   4198794  2014-05       1
27     s189447   5193727  2015-04       1
28     s103417   4842975  2014-12       1
29      s80355   4880503  2014-12       1
...        ...       ...      ...     ...
49571  p220760   4447146  2014-08       1
49572  p220760   4660298  2014-10       1
49573  p220760   4176367  2014-05       1
49574  p220760   4823601  2014-12       1
49575  p220760   4442437  2014-08       1
49576  p220760   4823389  2014-12       1
49577  p220760   4829748  2014-12       1
49578  p220760   5429657  2015-06       1
49579  p220760   4924313  2015-01       1
49580  p221113   5144309  2015-03       1
49581  p221113   4132780  2014-04       1
49582  p221113   4869320  2014-12       0
49583  p221113   4127015  2014-04       0
49584  p221113   4855658  2014-12       0
49585  p221113   3034410  2013-09       1
49586  p221113   2989767  2013-09       1
49587  p221113   2989766  2013-09       1
49588  p221536   5267594  2015-05       1
49589  p221536   5199034  2015-04       1
49590  p222737   4985497  2015-02       0
49591  p222737   5319639  2015-05       0
49592  p223558   5494218  2015-07       0
49593  p223558   4451159  2014-08       0
49594  p223854   3106982  2013-11       0
49595  p224528   5541435  2015-07       0
49596  p224528   5564573  2015-07       0
49597  p224528   5457038  2015-06       0
49598  p224709   5208593  2015-04       1
49599  p224709   5193875  2015-04       1
49600  p224709   5211131  2015-04       1

[49601 rows x 4 columns]

In [643]:
new_project = project.groupby(['EID']).size().reset_index().rename(columns = {0: 'project_count'})
project_home = project.groupby(['EID', 'IFHOME'])['TYPECODE'].count().unstack().add_prefix('PROJECT_IFHOME_').add_suffix('_count').reset_index()
last_project = project['DJDATE'].groupby(project.EID).max().reset_index()
last_project['DJDATE'] = last_project['DJDATE'].apply(translateYear)

In [644]:
last_project.DJDATE.unique()

array([  7,   8,   6,  -1,   3,  -5,   1,   5, -13, -15, -12, -11,   2,
         4,  -2,   0,  -7,  -6, -10, -14,  -9,  -3,  -4,  -8])

In [645]:
new_project1 = pd.merge(new_project, project_home, on = 'EID', how = 'left')
new_project2 = pd.merge(new_project1, last_project, on = 'EID', how = 'left')

new_project2.fillna(0, inplace = True)

version 2

In [646]:
# *
project_in2015_count = project[project.DJDATE >= '2015-01'].groupby(['EID']).size().reset_index().rename(columns = {0: 'project_in2015_count'})

new_project3 = pd.merge(new_project2, project_in2015_count, on = 'EID', how = 'left')
new_project3.fillna(0, inplace = True)

In [647]:
projectDAE = new_project3.copy()

In [648]:
train6 = pd.merge(train5, projectDAE, on = 'EID', how = 'left')
test6 = pd.merge(test5, projectDAE, on = 'EID', how = 'left')

# Lawsuit Feature

In [649]:
lawsuit = pd.read_csv(data_path + '7lawsuit.csv')

In [650]:
lawsuit

           EID   TYPECODE  LAWDATE  LAWAMOUNT
0         p155  107760058  2015-08          0
1         p155  102314636  2015-05          0
2         p293  110135120  2015-08      11400
3         p293  105635464  2015-08      15800
4         p293   78284856  2014-01      34000
5         p293   85369661  2014-01      34000
6         p293   77996859  2014-01      34000
7         p293   72630399  2013-12      19000
8         p342   13910277  2014-07     171600
9         p342   93353097  2014-07     171600
10        p342   93353101  2014-07     119100
11        p354   74644787  2012-11      18300
12        p494  101032010  2015-04       8800
13        p494   74796086  2013-09      68000
14        p494   74793086  2013-06       1900
15        p494  113213507  2015-04       8800
16        p559   97909249  2015-02      20000
17        p559   97739966  2015-01     137700
18        p587  110485751  2015-08      28000
19        p587  106590233  2015-08      28000
20        p628  109142579  2015-06      36100
21        p636  106036378  2015-06     107700
22        p651   60448349  2013-01       4900
23        p706  107754949  2014-12    2834800
24        p706   95961327  2014-12    2834800
25        p786   88731249  2014-10      10100
26        p828   98947431  2014-12    5691000
27        p828  106604776  2015-06    4777600
28        p841  100545566  2015-04    2133400
29        p841  105444748  2015-04    2133400
...        ...        ...      ...        ...
40072  s203102   66083918  2013-04    5034400
40073  s203102   91893481  2014-07      30600
40074  s246190  100175442  2015-04       8600
40075   s53962   91778358  2013-12      10300
40076   s53962   72817825  2013-12      10300
40077   s53962   97803133  2013-12      10300
40078  s458874   85357874  2014-08      18200
40079  s458874   86797028  2014-09      10300
40080  s458874   97790342  2014-09      10300
40081  s458874   97789593  2014-08      18200
40082  s458874   91896153  2014-09      10300
40083  s423254   93694876  2014-12     237400
40084  s423254   93694885  2014-12     237400
40085  s423254   93694882  2014-12     226000
40086  s423254   93694879  2014-12     237400
40087  s330894   62207066  2013-01          0
40088  s454499   44079028  2012-11      50800
40089  s283757   91793202  2014-10        800
40090  s114577   67682954  2013-08       2300
40091  s364421   62287239  2013-06     308700
40092   s34527   97935980  2014-07     537200
40093   s34527   75064327  2014-01      39300
40094  s299800   81317511  2014-02      14200
40095  s299800   75061312  2014-02      14200
40096  s338328   66080742  2012-10     106700
40097  s367236  105609431  2015-08      10300
40098  s332772  105029845  2015-06      10500
40099  s332772  109043907  2015-06      10500
40100  s332772  102528271  2015-06      10500
40101  s332772   42076637  2012-09      20800

[40102 rows x 4 columns]

In [651]:
lawsuit.LAWDATE.unique()

array(['2015-08', '2015-05', '2014-01', '2013-12', '2014-07', '2012-11',
       '2015-04', '2013-09', '2013-06', '2015-02', '2015-01', '2015-06',
       '2013-01', '2014-12', '2014-10', '2013-05', '2014-05', '2014-06',
       '2015-07', '2012-12', '2014-02', '2014-03', '2015-03', '2013-11',
       '2012-09', '2013-03', '2012-10', '2014-09', '2013-10', '2013-04',
       '2014-11', '2013-02', '2013-08', '2013-07', '2014-08', '2014-04'], dtype=object)

In [652]:
new_lawsuit = lawsuit.groupby(['EID']).size().reset_index().rename(columns = {0: 'lawsuit_count'})

lawsuit_sta = lawsuit.groupby(['EID']).LAWAMOUNT.agg([sum, max, min, np.mean, np.median])
lawsuit_sta['gap'] = lawsuit_sta['max'] -  lawsuit_sta['min']
lawsuit_sta = lawsuit_sta.add_prefix('lawsuit_LAWAMOUNT_').reset_index()
lawsuit_date = lawsuit['LAWDATE'].groupby(lawsuit.EID).agg([max, min]).add_prefix('lawsuit_LAWDATE_').reset_index()

lawsuit_date['lawsuit_LAWDATE_max'] = lawsuit_date['lawsuit_LAWDATE_max'].apply(translateYear)
lawsuit_date['lawsuit_LAWDATE_min'] = lawsuit_date['lawsuit_LAWDATE_min'].apply(translateYear)
lawsuit_date['lawsuit_LAWDATE_gap'] = lawsuit_date['lawsuit_LAWDATE_max'] - lawsuit_date['lawsuit_LAWDATE_min']

new_lawsuit1 = pd.merge(new_lawsuit, lawsuit_sta, on = 'EID', how = 'left')
new_lawsuit2 = pd.merge(new_lawsuit1, lawsuit_date, on = 'EID', how = 'left')

version 2.1

In [653]:
lawsuit_in2015 = lawsuit[lawsuit.LAWDATE >= '2015-01-01']
lawsuit_in2015_count = lawsuit_in2015.groupby(['EID']).size().reset_index().rename(columns = {0: 'lawsuit_in2015_count'})
lawsuit_in2015_sta = lawsuit_in2015.groupby(['EID'])['LAWAMOUNT'].agg([sum, max, min, np.mean])
lawsuit_in2015_sta['gap'] = lawsuit_in2015_sta['max'] -  lawsuit_in2015_sta['min']
lawsuit_in2015_sta = lawsuit_in2015_sta.add_prefix('lawsuit_LAWAMOUNT_2015_').reset_index()

new_lawsuit3 = pd.merge(new_lawsuit2, lawsuit_in2015_count, on = 'EID', how = 'left')
new_lawsuit4 = pd.merge(new_lawsuit3, lawsuit_in2015_sta, on = 'EID', how = 'left')
new_lawsuit4.fillna(0, inplace = True)

In [654]:
new_lawsuit4

,EID,lawsuit_count,lawsuit_LAWAMOUNT_sum,lawsuit_LAWAMOUNT_max,lawsuit_LAWAMOUNT_min,lawsuit_LAWAMOUNT_mean,lawsuit_LAWAMOUNT_median,lawsuit_LAWAMOUNT_gap,lawsuit_LAWDATE_max,lawsuit_LAWDATE_min,lawsuit_LAWDATE_gap,lawsuit_in2015_count,lawsuit_LAWAMOUNT_2015_sum,lawsuit_LAWAMOUNT_2015_max,lawsuit_LAWAMOUNT_2015_min,lawsuit_LAWAMOUNT_2015_mean,lawsuit_LAWAMOUNT_2015_gap
0,p100022,2,122000,61000,61000,6.100000e+04,61000.0,0,-4,-4,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
1,p100048,2,22000,11000,11000,1.100000e+04,11000.0,0,0,0,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
2,p100074,3,8646200,5509600,17100,2.882067e+06,3119500.0,5492500,6,3,3,3.0,8646200.0,5509600.0,17100.0,2.882067e+06,5492500.0
3,p100084,2,1488400,744200,744200,7.442000e+05,744200.0,0,-11,-11,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
4,p100107,2,2,1,1,1.000000e+00,1.0,0,-16,-16,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
5,p100129,1,118900,118900,118900,1.189000e+05,118900.0,0,-27,-27,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
6,p100165,1,51100,51100,51100,5.110000e+04,51100.0,0,3,3,0,1.0,51100.0,51100.0,51100.0,5.110000e+04,0.0
7,p100186,1,26700,26700,26700,2.670000e+04,26700.0,0,7,7,0,1.0,26700.0,26700.0,26700.0,2.670000e+04,0.0
8,p100253,11,3002800,3000000,0,2.729818e+05,0.0,3000000,7,-25,32,9.0,0.0,0.0,0.0,0.000000e+00,0.0
9,p100270,1,5361700,5361700,5361700,5.361700e+06,5361700.0,0,3,3,0,1.0,5361700.0,5361700.0,5361700.0,5.361700e+06,0.0
10,p100303,3,14500,5100,4500,4.833333e+03,4900.0,600,7,7,0,3.0,14500.0,5100.0,4500.0,4.833333e+03,600.0
11,p100327,2,692300,485300,207000,3.461500e+05,346150.0,278300,-4,-19,15,0.0,0.0,0.0,0.0,0.000000e+00,0.0
12,p100344,12,653636800,86748300,16580800,5.446973e+07,54955450.0,70167500,8,5,3,12.0,653636800.0,86748300.0,16580800.0,5.446973e+07,70167500.0
13,p100347,9,3156400,1128300,4400,3.507111e+05,181600.0,1123900,3,-14,17,1.0,184100.0,184100.0,184100.0,1.841000e+05,0.0
14,p100436,1,17720300,17720300,17720300,1.772030e+07,17720300.0,0,3,3,0,1.0,17720300.0,17720300.0,17720300.0,1.772030e+07,0.0
15,p100521,1,2428500,2428500,2428500,2.428500e+06,2428500.0,0,8,8,0,1.0,2428500.0,2428500.0,2428500.0,2.428500e+06,0.0
16,p100625,1,51400,51400,51400,5.140000e+04,51400.0,0,-15,-15,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
17,p100667,2,2134600,1067300,1067300,1.067300e+06,1067300.0,0,7,7,0,2.0,2134600.0,1067300.0,1067300.0,1.067300e+06,0.0
18,p100694,2,1401000,1241000,160000,7.005000e+05,700500.0,1081000,6,4,2,2.0,1401000.0,1241000.0,160000.0,7.005000e+05,1081000.0
19,p100764,1,9800,9800,9800,9.800000e+03,9800.0,0,-17,-17,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
20,p100825,9,99500,30000,2600,1.105556e+04,8500.0,27400,1,-24,25,0.0,0.0,0.0,0.0,0.000000e+00,0.0
21,p100846,2,80200,40100,40100,4.010000e+04,40100.0,0,-18,-18,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
22,p100864,3,24004700,13060000,5000000,8.001567e+06,5944700.0,8060000,2,-20,22,1.0,5000000.0,5000000.0,5000000.0,5.000000e+06,0.0
23,p100920,1,20000,20000,20000,2.000000e+04,20000.0,0,-11,-11,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
24,p100929,3,1,1,0,3.333333e-01,0.0,1,8,-4,12,2.0,0.0,0.0,0.0,0.000000e+00,0.0
25,p100933,1,500100,500100,500100,5.001000e+05,500100.0,0,-25,-25,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
26,p101000,7,15000,5400,900,2.142857e+03,900.0,4500,-10,-13,3,0.0,0.0,0.0,0.0,0.000000e+00,0.0
27,p101030,5,64600,18800,9000,1.292000e+04,9000.0,9800,8,5,3,5.0,64600.0,18800.0,9000.0,1.292000e+04,9800.0
28,p101171,8,6615800,3676200,2800,8.269750e+05,395650.0,3673400,4,-9,13,3.0,5222200.0,3676200.0,339200.0,1.740733e+06,3337000.0
29,p101182,2,12500,7200,5300,6.250000e+03,6250.0,1900,-3,-4,1,0.0,0.0,0.0,0.0,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10118,s9790,2,1757800,878900,878900,8.789000e+05,878900.0,0,6,6,0,2.0,1757800.0,878900.0,878900.0,8.789000e+05,0.0
10119,s97939,1,10000,10000,10000,1.000000e+04,10000.0,0,-27,-27,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10120,s9795,2,6400,3200,3200,3.200000e+03,3200.0,0,7,7,0,2.0,6400.0,3200.0,3200.0,3.200000e+03,0.0
10121,s97952,1,7700,7700,7700,7.700000e+03,7700.0,0,5,5,0,1.0,7700.0,7700.0,7700.0,7.700000e+03,0.0
10122,s98181,3,138900,62400,14100,4.630000e+04,62400.0,48300,2,-11,13,2.0,124800.0,62400.0,62400.0,6.240000e+04,0.0
10123,s98199,2,5625200,2812600,2812600,2.812600e+06,2812600.0,0,-8,-8,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10124,s98257,26,2969800,1317100,900,1.142231e+05,13800.0,1316200,8,-27,35,8.0,1787000.0,1317100.0,2300.0,2.233750e+05,1314800.0
10125,s9828,2,2263000,1131500,1131500,1.131500e+06,1131500.0,0,-11,-11,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10126,s98283,1,560000,560000,560000,5.600000e+05,560000.0,0,6,6,0,1.0,560000.0,560000.0,560000.0,5.600000e+05,0.0
10127,s98366,2,39400,19700,19700,1.970000e+04,19700.0,0,-8,-8,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10128,s98681,1,105100,105100,105100,1.051000e+05,105100.0,0,-21,-21,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10129,s9875,2,166400,83200,83200,8.320000e+04,83200.0,0,-8,-8,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10130,s98755,1,55700,55700,55700,5.570000e+04,55700.0,0,-11,-11,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10131,s98818,3,72300,24100,24100,2.410000e+04,24100.0,0,-7,-7,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10132,s98846,1,128900,128900,128900,1.289000e+05,128900.0,0,-18,-18,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10133,s98850,2,57400,43600,13800,2.870000e+04,28700.0,29800,-12,-12,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10134,s98931,5,3434400,1345500,100000,6.868800e+05,321700.0,1245500,2,-20,22,1.0,321700.0,321700.0,321700.0,3.217000e+05,0.0
10135,s98981,5,1052700,352700,0,2.105400e+05,350000.0,352700,8,-10,18,4.0,700000.0,350000.0,0.0,1.750000e+05,350000.0
10136,s99051,3,14100,5500,3600,4.700000e+03,5000.0,1900,-23,-26,3,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10137,s99066,1,34900,34900,34900,3.490000e+04,34900.0,0,0,0,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10138,s99084,7,658500,205800,3800,9.407143e+04,81500.0,202000,4,-17,21,1.0,21000.0,21000.0,21000.0,2.100000e+04,0.0
10139,s99122,4,115200,43700,17900,2.880000e+04,26800.0,25800,-6,-6,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10140,s99418,2,6200,3100,3100,3.100000e+03,3100.0,0,8,8,0,2.0,6200.0,3100.0,3100.0,3.100000e+03,0.0
10141,s99466,2,120300,101200,19100,6.015000e+04,60150.0,82100,4,-4,8,1.0,101200.0,101200.0,101200.0,1.012000e+05,0.0
10142,s99653,1,598900,598900,598900,5.989000e+05,598900.0,0,-26,-26,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10143,s99717,2,368000,350000,18000,1.840000e+05,184000.0,332000,-3,-6,3,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10144,s99733,1,40696000,40696000,40696000,4.069600e+07,40696000.0,0,-14,-14,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10145,s99797,1,0,0,0,0.000000e+00,0.0,0,-21,-21,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10146,s99809,1,10000,10000,10000,1.000000e+04,10000.0,0,-2,-2,0,0.0,0.0,0.0,0.0,0.000000e+00,0.0
10147,s99842,5,15482600,5000000,169100,3.096520e+06,3113500.0,4830900,-6,-24,18,0.0,0.0,0.0,0.0,0.000000e+00,0.0

In [655]:
lawsuitDAE = new_lawsuit4.copy()

In [656]:
train7 = pd.merge(train6, lawsuitDAE, on = 'EID', how = 'left')
test7 = pd.merge(test6, lawsuitDAE, on = 'EID', how = 'left')

# Breakfaith Feautre

In [657]:
breakfaith = pd.read_csv(data_path + '8breakfaith.csv')

In [658]:
breakfaith

          EID   TYPECODE    FBDATE SXENDDATE
0        p293     432341  2014年08月       NaN
1        p342   82982060  2014年08月       NaN
2        p342     312751  2014年08月       NaN
3        p816   98741001  2015年03月       NaN
4        p816    1349372  2015年03月       NaN
5        p825   98949341  2015年05月       NaN
6        p825    1627918  2015年05月       NaN
7        p845     724299  2014年11月   2015-07
8       p1096   60556535  2014年10月       NaN
9       p1096   64318506  2014年10月       NaN
10      p1096   60555872  2014年10月       NaN
11      p1096   60561735  2014年10月       NaN
12      p1096   60561806  2014年10月       NaN
13      p1096   60556474  2014年10月       NaN
14      p1096   60561542  2014年10月       NaN
15      p1096   60561606  2014年10月       NaN
16      p1096   60561483  2014年10月       NaN
17      p1096   60561680  2014年10月       NaN
18      p1096   60556035  2014年10月       NaN
19      p1096   42401939  2013年10月       NaN
20      p1096      16065  2013年10月       NaN
21      p1096     538288  2014年10月       NaN
22      p1096     565851  2014年10月       NaN
23      p1096     566131  2014年10月       NaN
24      p1096     566895  2014年10月       NaN
25      p1096     567197  2014年10月       NaN
26      p1096     567098  2014年10月       NaN
27      p1096     566970  2014年10月       NaN
28      p1096     567265  2014年10月       NaN
29      p1096     565968  2014年10月       NaN
...       ...        ...       ...       ...
4358   s32992   92400588  2015年03月       NaN
4359  s372606    1193368  2015年03月       NaN
4360  s372606   91748485  2015年03月       NaN
4361  s453712    1139649  2015年03月       NaN
4362  s453712   91671632  2015年03月       NaN
4363  s267822      29703  2013年10月       NaN
4364  s267822   44187946  2013年10月       NaN
4365   s20285     172986  2014年06月   2015-07
4366   s20285    1203969  2015年02月       NaN
4367  s135091     210970  2014年07月       NaN
4368  s234907     205015  2014年07月       NaN
4369  s234907    2071448  2015年07月       NaN
4370  s234907   37140286  2014年07月       NaN
4371  s272764     173687  2014年06月       NaN
4372  s272764    1485676  2015年05月       NaN
4373  s272764   96709363  2015年05月       NaN
4374  s272764   27141017  2014年06月       NaN
4375   s82660    2090847  2015年07月       NaN
4376   s82660  104115617  2015年07月       NaN
4377  s284729     920569  2015年01月       NaN
4378  s284729   91009515  2015年01月       NaN
4379  s203102     591581  2014年10月       NaN
4380  s203102     591589  2014年10月       NaN
4381  s203102       5683  2013年10月       NaN
4382  s203102     108575  2014年03月       NaN
4383  s203102   83557915  2014年10月       NaN
4384  s203102   83557913  2014年10月       NaN
4385  s203102   66083918  2014年03月       NaN
4386   s34527     272318  2014年08月       NaN
4387   s34527   83521369  2014年08月       NaN

[4388 rows x 4 columns]

In [659]:
new_breakfaith = breakfaith.groupby(breakfaith.EID).size().reset_index().rename(columns = {0: 'breakfaith_count'})
not_end_breakfaith = breakfaith[breakfaith.SXENDDATE.isnull()].groupby(breakfaith.EID).size().reset_index().rename(columns = {0: 'not_end_breakfaith_count'})
breakfaith_date = breakfaith.groupby(breakfaith.EID)['FBDATE'].agg([max, min]).add_prefix('breakfaith_date_').reset_index()
breakfaith_date['breakfaith_date_max'] = breakfaith_date['breakfaith_date_max'].apply(translateYearFB)
breakfaith_date['breakfaith_date_min'] = breakfaith_date['breakfaith_date_min'].apply(translateYearFB)
breakfaith_date['breakfaith_date_gap'] = breakfaith_date['breakfaith_date_max'] - breakfaith_date['breakfaith_date_min']


new_breakfaith1 = pd.merge(new_breakfaith, not_end_breakfaith, on = 'EID', how = 'left')
new_breakfaith2 = pd.merge(new_breakfaith1, breakfaith_date, on = 'EID', how = 'left')
new_breakfaith2['not_end_breakfaith_rate'] = new_breakfaith2['not_end_breakfaith_count'] / new_breakfaith2['breakfaith_count']

# rate=0 代表所有失信记录全部结束 1 代表全部没结束
new_breakfaith2.fillna(0, inplace = True)

In [660]:
breakfaithDAE = new_breakfaith2.copy()

In [661]:
train8 = pd.merge(train7, breakfaithDAE, on = 'EID', how = 'left')
test8 = pd.merge(test7, breakfaithDAE, on = 'EID', how = 'left')

In [662]:
test7

,EID,PROV,RGYEAR,HY,ZCZB,ETYPE,MPNUM,INUM,ENUM,FINZB,...,lawsuit_LAWAMOUNT_gap,lawsuit_LAWDATE_max,lawsuit_LAWDATE_min,lawsuit_LAWDATE_gap,lawsuit_in2015_count,lawsuit_LAWAMOUNT_2015_sum,lawsuit_LAWAMOUNT_2015_max,lawsuit_LAWAMOUNT_2015_min,lawsuit_LAWAMOUNT_2015_mean,lawsuit_LAWAMOUNT_2015_gap
0,p10000,11,2011,51.0,10.0,6,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,p100001,11,2011,39.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,p100006,11,2015,18.0,100.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,p100009,11,2015,52.0,5.0,8,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,p10001,11,2014,51.0,100.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,p100010,11,2008,52.0,10.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,p100014,11,2013,51.0,10.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,p10002,11,2015,51.0,200.0,6,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,p100027,11,2014,52.0,10.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,p100028,11,2006,51.0,300.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,p100029,11,2014,72.0,200.0,7,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,p10003,11,2008,72.0,10.0,6,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,p100030,11,2010,33.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,p100033,11,2005,52.0,2.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,p100034,11,2011,51.0,50.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,p100035,11,2013,62.0,3.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,p100037,11,2012,51.0,600.0,7,4.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,p100042,11,2013,70.0,100.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,p100043,11,2013,51.0,100.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,p100045,11,2015,52.0,30.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,p100046,11,2013,72.0,50.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,p10005,11,2012,51.0,20.0,6,4.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,p100051,11,2009,40.0,50.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,p100054,11,2014,51.0,10.0,7,3.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,p100057,11,2013,51.0,500.0,7,2.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,p100058,11,2011,39.0,200.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,p100061,11,2012,20.0,330.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,p100062,11,2012,34.0,50.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,p100063,11,2015,51.0,100.0,7,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,p100066,11,1994,51.0,50.0,7,4.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218217,s99866,12,2011,72.0,10.0,17,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218218,s99867,12,2013,74.0,40.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218219,s99873,12,2011,72.0,440.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218220,s99876,12,2012,75.0,1000.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218221,s99883,12,2009,75.0,100.0,7,8.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218222,s99885,12,2010,87.0,300.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218223,s99886,12,2012,51.0,10.0,7,1.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218224,s99892,12,2008,52.0,200.0,7,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218225,s99893,12,1998,87.0,200.0,6,1.0,3.0,1.0,2160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218226,s99894,12,2011,87.0,30.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218227,s99895,12,2015,87.0,200.0,7,3.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218228,s99903,12,1992,78.0,300.0,13,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218229,s99916,12,2013,51.0,100.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218230,s99918,12,2005,72.0,3.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218231,s99920,12,2007,75.0,10.0,7,19.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218232,s99926,12,2015,75.0,1000.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218233,s99937,12,2014,52.0,500.0,7,3.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218234,s99938,12,2012,75.0,500.0,7,4.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218235,s99948,12,2013,52.0,10.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218236,s99949,12,2013,72.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218237,s99950,12,2006,87.0,5.0,7,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218238,s99951,12,2015,75.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218239,s99959,12,2012,52.0,10.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218240,s99965,12,2010,52.0,50.0,7,3.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218241,s99972,12,2014,51.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218242,s99976,12,2011,29.0,5.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218243,s99978,12,1994,51.0,6.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218244,s99993,12,2007,51.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218245,s99996,12,2009,82.0,50.0,17,7.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218246,s99998,12,2009,52.0,200.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Recruit Feature

In [663]:
recruit = pd.read_csv(data_path + '9recruit.csv')

def cleanPNUM(df):
    data = df['PNUM'].fillna('0').values
    pnum = []
    for row in data:
        if '人' in row:
            #print row
            row = int(row[:-1])
        elif row!='若干':
            row = int(row)
        elif row=='若干':
            row = 4.7
        pnum.append(row)

    df['PNUM'] = pnum
    return df


# In[107]:

recruit = cleanPNUM(recruit)

/opt/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [664]:
recruit.RECDATE.unique()

array(['2014-05', '2014-06', '2015-08', '2014-07', '2015-03', '2014-08',
       '2015-04', '2014-09', '2015-07', '2014-10', '2014-11', '2015-06',
       '2014-12', '2015-05', '2015-01', '2015-02', '2014-04', '2014-01',
       '2013-12', '2013-11', '2013-10', '2013-07', '2014-03', '2013-09',
       '2013-08', '2014-02', '2013-04', '2013-06', '2013-05', '2013-03',
       '2008-08', '2012-12', '2012-04'], dtype=object)

In [665]:
recruit.columns

Index(['EID', 'WZCODE', 'POSCODE', 'RECDATE', 'PNUM'], dtype='object')

In [666]:
new_recurit = recruit.groupby(recruit.EID).size().reset_index().rename(columns = {0: 'recurit_count'})

recruit_type = recruit.groupby(['EID', 'WZCODE'])['PNUM'].sum().unstack().add_prefix('WZCODE_').add_suffix('_count').reset_index()
recruit_type.fillna(0, inplace = True)
recurit_2015 = recruit[recruit.RECDATE >= '2015-01']
recurit_2015_count = recurit_2015.groupby(recurit_2015.EID)['PNUM'].sum().reset_index().rename(columns = {0: 'recurit2015_count'})

new_recurit1 = pd.merge(new_recurit,recruit_type , on = 'EID', how = 'left')
new_recurit2 = pd.merge(new_recurit1,recurit_2015_count , on = 'EID', how = 'left')

new_recurit2.fillna(0, inplace = True)

In [667]:
recruit_type

WZCODE      EID  WZCODE_zp01_count  WZCODE_zp02_count  WZCODE_zp03_count
0       p100004                0.0                8.0               24.0
1       p100008                4.0                0.0               23.5
2       p100032                0.0                0.0                6.0
3       p100037                1.0                4.0               22.0
4       p100038                0.0                4.7               10.4
5       p100049                0.0               14.1                0.0
6       p100057                6.0               76.1                7.0
7       p100072                0.0                6.0                0.0
8       p100087                0.0                2.0               14.1
9       p100089                0.0               10.0                0.0
10      p100138                0.0                0.0               29.7
11      p100154                0.0                9.0               15.0
12      p100162                0.0                0.0               10.7
13      p100177                0.0               16.0                0.0
14       p10019                0.0                0.0                8.0
15      p100253                0.0                7.0                0.0
16      p100255                0.0                0.0               10.0
17      p100287                2.0                0.0                6.0
18      p100288                2.0                0.0                0.0
19      p100291                0.0                0.0                7.0
20      p100296                0.0                0.0               10.0
21      p100314                0.0                0.0                4.7
22      p100337                1.0                0.0                0.0
23      p100352                0.0                9.4                0.0
24       p10039                0.0               77.7               33.0
25      p100442                0.0                0.0               16.0
26      p100480                0.0                0.0                6.0
27      p100527                5.0               10.0                0.0
28      p100615                0.0                0.0                2.0
29      p100626                0.0                0.0                7.0
...         ...                ...                ...                ...
41847    s99465                2.0                6.0               14.7
41848    s99466                0.0              238.5                0.0
41849    s99483                0.0                4.0                0.0
41850    s99502                1.0                0.0                0.0
41851    s99511               17.0              140.1                0.0
41852    s99532                0.0               15.0               23.7
41853    s99605                9.0                0.0                0.0
41854    s99618                0.0               15.7                0.0
41855    s99668                0.0               24.1                0.0
41856    s99678                0.0                0.0               16.0
41857    s99680                0.0               43.0                0.0
41858    s99687                6.0              817.5                0.0
41859     s9970                0.0               16.0               23.7
41860    s99750                0.0                0.0               16.1
41861     s9976                0.0                0.0               79.9
41862    s99789                0.0               12.0                0.0
41863    s99791                0.0                4.0                0.0
41864    s99809                0.0              273.1               20.0
41865    s99819               12.0               17.0                9.0
41866    s99830                0.0                0.0               24.0
41867    s99855                0.0                0.0               74.2
41868    s99859                0.0               70.0                0.0
41869    s99883                0.0              123.4                0.0
41870    s99894                0.0               10.0                0.0
41871    s99899                0.0                0.0               27.7
41872    s99904                0.0               11.4                4.7
41873    s99938                2.0               83.7                0.0
41874    s99955                0.0               57.4                0.0
41875    s99988                2.0                0.0                0.0
41876    s99996                0.0                0.0              140.0

[41877 rows x 4 columns]

version 2 （有效果）

In [668]:
recruit_type1 = pd.DataFrame(recruit_type['WZCODE_zp01_count'] +  recruit_type['WZCODE_zp02_count'] +  recruit_type['WZCODE_zp03_count'], columns = ['recurit_sum'])

# **
recruit_type1['EID'] = recruit_type.EID
recruit_type1['zp01_rate'] =  recruit_type['WZCODE_zp01_count'] / recruit_type1['recurit_sum']
recruit_type1['zp02_rate'] =  recruit_type['WZCODE_zp02_count'] / recruit_type1['recurit_sum']
recruit_type1['zp03_rate'] =  recruit_type['WZCODE_zp03_count'] / recruit_type1['recurit_sum']
recruit_type1.fillna(0, inplace = True)

new_recurit3 = pd.merge(new_recurit2, recruit_type1 , on = 'EID', how = 'left')

v3.4

In [669]:
"""new_recurit4 = pd.merge(new_recurit3, EID_HY_ETYPE, on = 'EID', how = 'left')

prefix_index = -3
new_recurit5 = get_HandE(new_recurit4, 'recurit_sum', prefix_index)

new_recurit5.drop(['ETYPE', 'HY'], axis = 1, inplace = True)"""

"new_recurit4 = pd.merge(new_recurit3, EID_HY_ETYPE, on = 'EID', how = 'left')\n\nprefix_index = -3\nnew_recurit5 = get_HandE(new_recurit4, 'recurit_sum', prefix_index)\n\nnew_recurit5.drop(['ETYPE', 'HY'], axis = 1, inplace = True)"

v4.4

In [670]:
recurit_newdate = recruit.copy()
recurit_newdate.RECDATE = recurit_newdate.RECDATE.apply(translateYearRECRUIT)


RECDATE_sta = recurit_newdate['RECDATE'].groupby(recurit_newdate.EID).agg([max, min])
RECDATE_sta['range'] = RECDATE_sta['max'] - RECDATE_sta['min']
RECDATE_sta = RECDATE_sta.add_prefix('recruit_RECDATE_').reset_index()

new_recurit4 = pd.merge(new_recurit3, RECDATE_sta , on = 'EID', how = 'left')

Merge Train and Test

In [671]:
recruitDAE = new_recurit4.copy()

In [672]:
train9 = pd.merge(train8, recruitDAE, on = 'EID', how = 'left')
test9 = pd.merge(test8, recruitDAE, on = 'EID', how = 'left')

In [673]:
test9

,EID,PROV,RGYEAR,HY,ZCZB,ETYPE,MPNUM,INUM,ENUM,FINZB,...,WZCODE_zp02_count,WZCODE_zp03_count,PNUM,recurit_sum,zp01_rate,zp02_rate,zp03_rate,recruit_RECDATE_max,recruit_RECDATE_min,recruit_RECDATE_range
0,p10000,11,2011,51.0,10.0,6,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,p100001,11,2011,39.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,p100006,11,2015,18.0,100.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,p100009,11,2015,52.0,5.0,8,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,p10001,11,2014,51.0,100.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,p100010,11,2008,52.0,10.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,p100014,11,2013,51.0,10.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,p10002,11,2015,51.0,200.0,6,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,p100027,11,2014,52.0,10.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,p100028,11,2006,51.0,300.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,p100029,11,2014,72.0,200.0,7,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,p10003,11,2008,72.0,10.0,6,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,p100030,11,2010,33.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,p100033,11,2005,52.0,2.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,p100034,11,2011,51.0,50.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,p100035,11,2013,62.0,3.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,p100037,11,2012,51.0,600.0,7,4.0,3.0,0.0,0.0,...,4.0,22.0,7.0,27.0,0.037037,0.148148,0.814815,88.0,77.0,11.0
17,p100042,11,2013,70.0,100.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,p100043,11,2013,51.0,100.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,p100045,11,2015,52.0,30.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,p100046,11,2013,72.0,50.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,p10005,11,2012,51.0,20.0,6,4.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,p100051,11,2009,40.0,50.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,p100054,11,2014,51.0,10.0,7,3.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,p100057,11,2013,51.0,500.0,7,2.0,5.0,0.0,0.0,...,76.1,7.0,39.4,89.1,0.067340,0.854097,0.078563,89.0,79.0,10.0
25,p100058,11,2011,39.0,200.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,p100061,11,2012,20.0,330.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,p100062,11,2012,34.0,50.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,p100063,11,2015,51.0,100.0,7,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,p100066,11,1994,51.0,50.0,7,4.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218217,s99866,12,2011,72.0,10.0,17,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218218,s99867,12,2013,74.0,40.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218219,s99873,12,2011,72.0,440.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218220,s99876,12,2012,75.0,1000.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218221,s99883,12,2009,75.0,100.0,7,8.0,2.0,0.0,0.0,...,123.4,0.0,0.0,123.4,0.000000,1.000000,0.000000,79.0,73.0,6.0
218222,s99885,12,2010,87.0,300.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218223,s99886,12,2012,51.0,10.0,7,1.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218224,s99892,12,2008,52.0,200.0,7,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218225,s99893,12,1998,87.0,200.0,6,1.0,3.0,1.0,2160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218226,s99894,12,2011,87.0,30.0,7,0.0,1.0,0.0,0.0,...,10.0,0.0,10.0,10.0,0.000000,1.000000,0.000000,91.0,91.0,0.0
218227,s99895,12,2015,87.0,200.0,7,3.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218228,s99903,12,1992,78.0,300.0,13,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218229,s99916,12,2013,51.0,100.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218230,s99918,12,2005,72.0,3.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218231,s99920,12,2007,75.0,10.0,7,19.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218232,s99926,12,2015,75.0,1000.0,7,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218233,s99937,12,2014,52.0,500.0,7,3.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218234,s99938,12,2012,75.0,500.0,7,4.0,2.0,0.0,0.0,...,83.7,0.0,48.8,85.7,0.023337,0.976663,0.000000,92.0,73.0,19.0
218235,s99948,12,2013,52.0,10.0,7,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218236,s99949,12,2013,72.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218237,s99950,12,2006,87.0,5.0,7,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218238,s99951,12,2015,75.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218239,s99959,12,2012,52.0,10.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218240,s99965,12,2010,52.0,50.0,7,3.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218241,s99972,12,2014,51.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218242,s99976,12,2011,29.0,5.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218243,s99978,12,1994,51.0,6.0,8,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218244,s99993,12,2007,51.0,50.0,7,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218245,s99996,12,2009,82.0,50.0,17,7.0,2.0,0.0,0.0,...,0.0,140.0,0.0,140.0,0.000000,0.000000,1.000000,78.0,77.0,1.0
218246,s99998,12,2009,52.0,200.0,7,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Entbase_Alter Feature

version 3

In [674]:
ent_alter = pd.merge(cdf, entbase, on = 'EID', how ='left')
# HY ALTER 均值与差值

ent_alter_gb_HY = ent_alter.groupby(['HY']).size().reset_index().rename(columns = {0: 'ent_alter_HY_alterno_count'})
HY_EID_count = entbase.groupby(['HY']).size().reset_index().rename(columns = {0: 'entbase_HY_EID_count'})

ent_alter_gb_HY1 = pd.merge(ent_alter_gb_HY, HY_EID_count, on = 'HY', how = 'left')
ent_alter_gb_HY1['ent_alter_HY_alterno_mean'] = ent_alter_gb_HY1['ent_alter_HY_alterno_count'] / ent_alter_gb_HY1['entbase_HY_EID_count']
ent_alter_gb_HY2 = ent_alter_gb_HY1.drop(['ent_alter_HY_alterno_count' , 'entbase_HY_EID_count'], axis = 1)


# ETYPE ALTER 均值与差值
ent_alter_gb_ETYPE = ent_alter.groupby(['ETYPE']).size().reset_index().rename(columns = {0: 'ent_alter_ETYPE_alterno_count'})
ETYPE_EID_count = entbase.groupby(['ETYPE']).size().reset_index().rename(columns = {0: 'entbase_ETYPE_EID_count'})

ent_alter_gb_ETYPE1 = pd.merge(ent_alter_gb_ETYPE, ETYPE_EID_count, on = 'ETYPE', how = 'left')
ent_alter_gb_ETYPE1['ent_alter_ETYPE_alterno_mean'] = ent_alter_gb_ETYPE1['ent_alter_ETYPE_alterno_count'] / ent_alter_gb_ETYPE1['entbase_ETYPE_EID_count']
ent_alter_gb_ETYPE2 = ent_alter_gb_ETYPE1.drop(['ent_alter_ETYPE_alterno_count' , 'entbase_ETYPE_EID_count'], axis = 1)

ent_alter_gb_HY_ETYPE = ent_alter.groupby(['ETYPE', 'HY']).size().reset_index().rename(columns = {0: 'ent_alter_ETYPE_alterno_count'})
ETYPE_EID_count = entbase.groupby(['ETYPE']).size().reset_index().rename(columns = {0: 'entbase_ETYPE_EID_count'})

ent_alter_gb_ETYPE1 = pd.merge(ent_alter_gb_ETYPE, ETYPE_EID_count, on = 'ETYPE', how = 'left')
ent_alter_gb_ETYPE1['ent_alter_ETYPE_alterno_mean'] = ent_alter_gb_ETYPE1['ent_alter_ETYPE_alterno_count'] / ent_alter_gb_ETYPE1['entbase_ETYPE_EID_count']
ent_alter_gb_ETYPE2 = ent_alter_gb_ETYPE1.drop(['ent_alter_ETYPE_alterno_count' , 'entbase_ETYPE_EID_count'], axis = 1)

In [675]:
train10 = pd.merge(train9, ent_alter_gb_HY2, on = 'HY', how = 'left')
train11 = pd.merge(train10, ent_alter_gb_ETYPE2, on = 'ETYPE', how = 'left')
train11.ent_alter_ETYPE_alterno_mean.fillna(0, inplace = True)
train11.ent_alter_HY_alterno_mean.fillna(0, inplace = True)
train11['ent_alter_HY_alterno_gap'] = train11['ALT_NUM'] - train11['ent_alter_HY_alterno_mean']
train11['ent_alter_ETYPE_alterno_gap'] = train11['ALT_NUM'] - train11['ent_alter_ETYPE_alterno_mean']

test10 = pd.merge(test9, ent_alter_gb_HY2, on = 'HY', how = 'left')
test11= pd.merge(test10, ent_alter_gb_ETYPE2, on = 'ETYPE', how = 'left')
test11.ent_alter_ETYPE_alterno_mean.fillna(0, inplace = True)
test11.ent_alter_HY_alterno_mean.fillna(0, inplace = True)
test11['ent_alter_HY_alterno_gap'] = test11['ALT_NUM'] - test11['ent_alter_HY_alterno_mean']
test11['ent_alter_ETYPE_alterno_gap'] = test11['ALT_NUM'] - test11['ent_alter_ETYPE_alterno_mean']

# Qualification

In [676]:
qualification = pd.read_csv(data_path + '10qualification.csv')

In [677]:
def translateYearQualification(date):
    if type(date) == float:
        return np.nan
    year = int(date[:4])
    month = int(date[-2:])
    return (year-2007)*12 + month

In [678]:
qualification_count = qualification.groupby(qualification.EID).size().reset_index().rename(columns = {0: 'qualification_count'})

new_qualification = qualification.copy()
new_qualification['BEGINDATE'] = new_qualification.BEGINDATE.apply(translateYearQualification)
new_qualification['EXPIRYDATE'] = new_qualification.EXPIRYDATE.apply(translateYearQualification)

qualification_type = new_qualification.groupby(['EID', 'ADDTYPE']).size().unstack().add_prefix('qualification_type_').add_suffix('_count').reset_index()
qualification_type.fillna(0, inplace = True)

qualification_bdate_sta = new_qualification.groupby(new_qualification.EID).BEGINDATE.agg([max, min]).add_prefix('Qua_Bdate_').reset_index()
qualification_bdate_sta['Qua_Bdate_range'] = qualification_bdate_sta['Qua_Bdate_max'] - qualification_bdate_sta['Qua_Bdate_min']
qualification_edate_sta = new_qualification.groupby(new_qualification.EID).EXPIRYDATE.agg([max, min]).add_prefix('Qua_Edate_').reset_index()

new_qualification2 = pd.merge(qualification_count, qualification_type, on = 'EID', how = 'left')
new_qualification3 = pd.merge(new_qualification2, qualification_bdate_sta, on = 'EID', how = 'left')
new_qualification4 = pd.merge(new_qualification3, qualification_edate_sta, on = 'EID', how = 'left')

In [679]:
qualificationDAE = new_qualification4.copy()

In [680]:
train12 = pd.merge(train11, qualificationDAE, on = 'EID', how = 'left')
test12 = pd.merge(test11, qualificationDAE, on = 'EID', how = 'left')

In [681]:
import copy
def get_nan_info(nan_train):
    tmp = copy.deepcopy(nan_train)
    tmp.fillna(-999, inplace = True)
    tmp['n_null'] = (tmp == -999).sum(axis=1)
    tmp['discret_null'] = tmp.n_null
    tmp.discret_null[tmp.discret_null<=40] = 1
    tmp.discret_null[(tmp.discret_null>40)&(tmp.discret_null<=73)] = 2
    tmp.discret_null[(tmp.discret_null>73)&(tmp.discret_null<=82)] = 3
    tmp.discret_null[(tmp.discret_null>82)&(tmp.discret_null<=85)] = 4
    tmp.discret_null[(tmp.discret_null>85)&(tmp.discret_null<=91)] = 5
    tmp.discret_null[(tmp.discret_null>91)&(tmp.discret_null<=100)] = 6
    tmp.discret_null[tmp.discret_null>100] = 7
    return tmp

In [682]:
temp = copy.deepcopy(train12)
temp1 = get_nan_info(temp)
train13 = pd.concat([train12, temp1[['discret_null']] ], axis = 1)

temp2 = copy.deepcopy(test12)
temp3 = get_nan_info(temp2)
test13 = pd.concat([test12, temp3[['discret_null']] ], axis = 1)

/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

# Save Feature (Remember change the file name)

In [683]:
#train13.drop(['ENDDATE_n'], axis = 1, inplace = True)

In [684]:
train13['len_EID_NUMBER'] = train13['EID_NUMBER'].apply(lambda x:int(x/20))
train13 = train13.drop(['EID_NUMBER'], axis=1)
test13['len_EID_NUMBER'] = test13['EID_NUMBER'].apply(lambda x:int(x/20))
test13 = test13.drop(['EID_NUMBER'], axis=1)

savetrain = train13.copy()
savetest = test13.copy()

In [ ]:
binlabel_train_cp = pd.read_csv(feature_path + 'binlabel_train_cp.csv')
binlabel_test_cp = pd.read_csv(feature_path + 'binlabel_test_cp.csv')


#bin_feature = pd.read_csv(feature_path + 't30_bin_feature.csv')

bin_label_train = pd.merge(savetrain, binlabel_train_cp, on = 'EID', how = 'left')
bin_label_test = pd.merge(savetest, binlabel_test_cp, on = 'EID', how = 'left')

bin_label_train.shape , bin_label_test.shape

bin_label_train.to_csv(feature_path + 'train_v1.8.csv', index = False)
bin_label_test.to_csv(feature_path + 'test_v1.8.csv', index = False)

In [696]:
#savetrain.to_csv(feature_path + 'train_v1.2.csv', index = False)
#savetest.to_csv(feature_path + 'test_v1.2.csv', index = False)